import type { PageContentMap } from "./types";

export const content: PageContentMap = {
  en: {
    faq: [
      { question: "What is the most common screen resolution?", answer: "StatCounter's March 2026 desktop screen-resolution data lists 1920 x 1080 (Full HD) as the top worldwide resolution at 21.16%. The next largest desktop buckets are 1536 x 864 at 9.22%, 1366 x 768 at 7.05%, 1280 x 720 at 4.06%, and 2560 x 1440 at 3.73%." },
      { question: "What is 4K resolution in pixels?", answer: "4K (also called UHD) is 3840 x 2160 pixels, exactly four times the pixel count of Full HD (1920 x 1080). Cinema 4K (DCI 4K) is slightly wider at 4096 x 2160 pixels." },
      { question: "Is QHD the same as 2K?", answer: "Not exactly. QHD is 2560 x 1440 pixels. True 2K (DCI 2K) is 2048 x 1080 pixels. However, QHD is commonly (if inaccurately) marketed as '2K' because its horizontal resolution is close to 2560." },
      { question: "How many pixels does 8K have?", answer: "8K resolution (7680 x 4320) contains 33.2 million pixels - 16 times the pixel count of Full HD. 8K displays are primarily used for professional video production and large-format commercial displays." },
    ],
    body: {
      heading1: "Common Display Resolutions",
      tableHead1: "Name",
      tableHead2: "Resolution (px)",
      tableHead3: "Aspect Ratio",
      tableHead4: "Total Pixels",
      heading2: "Resolutions by Device Type",
      heading2a: "Laptops",
      tableHead5: "Screen Size",
      tableHead6: "Common Resolutions",
      tableHead7: "PPI Range",
      heading2b: "Desktop Monitors",
      heading3: "Common Aspect Ratios",
      li1: "16:9 - Standard widescreen (most monitors, TVs, phones in landscape)",
      li2: "16:10 - Common for productivity laptops (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Ultrawide monitors (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Legacy (1024 x 768), still used in some tablets",
      li6: "3:2 - Surface devices, some Chromebooks (2256 x 1504)",
      heading4: "Choosing the Right Resolution",
      p1: "For general productivity, QHD (2560 x 1440) on a 27-inch monitor offers an excellent balance of screen real estate and text clarity at 109 PPI. For photo and video editing, 4K (3840 x 2160) provides the detail needed to evaluate fine image quality. For gaming, resolution should match your GPU capability - 1080p for budget setups, 1440p for mid-range, and 4K for high-end systems.",
      p2: "Check your current display resolution with our Screen Resolution Checker, or calculate pixel density with the PPI Calculator.",
    },
  },
  es: {
    faq: [
      { question: "¿Cuál es la resolución de pantalla más común?", answer: "En 2026, 1920 x 1080 (Full HD) sigue siendo la resolución de escritorio más común en todo el mundo, utilizada por aproximadamente el 55% de los usuarios de escritorio. 2560 x 1440 (QHD) es la segunda más común con alrededor del 15%." },
      { question: "¿Cuál es la resolución 4K en píxeles?", answer: "4K (también llamado UHD) es 3840 x 2160 píxeles, exactamente cuatro veces la cantidad de píxeles de Full HD (1920 x 1080). Cinema 4K (DCI 4K) es ligeramente más ancho con 4096 x 2160 píxeles." },
      { question: "¿QHD es lo mismo que 2K?", answer: "No exactamente. QHD es 2560 x 1440 píxeles. El verdadero 2K (DCI 2K) es 2048 x 1080 píxeles. Sin embargo, QHD se comercializa comúnmente (aunque incorrectamente) como '2K' porque su resolución horizontal está cerca de 2560." },
      { question: "¿Cuántos píxeles tiene 8K?", answer: "La resolución 8K (7680 x 4320) contiene 33.2 millones de píxeles - 16 veces la cantidad de píxeles de Full HD. Las pantallas 8K se usan principalmente para producción de video profesional y pantallas comerciales de gran formato." },
    ],
    body: {
      heading1: "Resoluciones de pantalla comunes",
      tableHead1: "Nombre",
      tableHead2: "Resolución (px)",
      tableHead3: "Proporción",
      tableHead4: "Píxeles totales",
      heading2: "Resoluciones por tipo de dispositivo",
      heading2a: "Portátiles",
      tableHead5: "Tamaño de pantalla",
      tableHead6: "Resoluciones comunes",
      tableHead7: "Rango PPI",
      heading2b: "Monitores de escritorio",
      heading3: "Proporciones de aspecto comunes",
      li1: "16:9 - Panorámica estándar (la mayoría de monitores, TVs, teléfonos en horizontal)",
      li2: "16:10 - Común para portátiles de productividad (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Monitores ultrawide (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Legado (1024 x 768), aún usado en algunas tablets",
      li6: "3:2 - Dispositivos Surface, algunos Chromebooks (2256 x 1504)",
      heading4: "Elegir la resolución correcta",
      p1: "Para productividad general, QHD (2560 x 1440) en un monitor de 27 pulgadas ofrece un excelente balance entre espacio de pantalla y claridad de texto a 109 PPI. Para edición de fotos y video, 4K (3840 x 2160) proporciona el detalle necesario para evaluar la calidad fina de imagen. Para juegos, la resolución debe coincidir con la capacidad de tu GPU - 1080p para configuraciones económicas, 1440p para gama media y 4K para sistemas de gama alta.",
      p2: "Verifica tu resolución de pantalla actual con nuestro Verificador de Resolución de Pantalla, o calcula la densidad de píxeles con la Calculadora de PPI.",
    },
  },
  fr: {
    faq: [
      { question: "Quelle est la résolution d'écran la plus courante ?", answer: "En 2026, 1920 x 1080 (Full HD) reste la résolution de bureau la plus courante au monde, utilisée par environ 55 % des utilisateurs de bureau. 2560 x 1440 (QHD) est la deuxième plus courante à environ 15 %." },
      { question: "Quelle est la résolution 4K en pixels ?", answer: "4K (aussi appelé UHD) est 3840 x 2160 pixels, exactement quatre fois le nombre de pixels du Full HD (1920 x 1080). Le Cinema 4K (DCI 4K) est légèrement plus large à 4096 x 2160 pixels." },
      { question: "Le QHD est-il identique au 2K ?", answer: "Pas exactement. Le QHD est 2560 x 1440 pixels. Le vrai 2K (DCI 2K) est 2048 x 1080 pixels. Cependant, le QHD est couramment (mais inexactement) commercialisé comme '2K' car sa résolution horizontale est proche de 2560." },
      { question: "Combien de pixels a le 8K ?", answer: "La résolution 8K (7680 x 4320) contient 33,2 millions de pixels - 16 fois le nombre de pixels du Full HD. Les écrans 8K sont principalement utilisés pour la production vidéo professionnelle et les écrans commerciaux grand format." },
    ],
    body: {
      heading1: "Résolutions d'affichage courantes",
      tableHead1: "Nom", tableHead2: "Résolution (px)", tableHead3: "Rapport d'aspect", tableHead4: "Pixels totaux",
      heading2: "Résolutions par type d'appareil",
      heading2a: "Ordinateurs portables",
      tableHead5: "Taille d'écran", tableHead6: "Résolutions courantes", tableHead7: "Plage PPI",
      heading2b: "Moniteurs de bureau",
      heading3: "Rapports d'aspect courants",
      li1: "16:9 - Grand écran standard (la plupart des moniteurs, TV, téléphones en paysage)",
      li2: "16:10 - Courant pour les portables de productivité (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Moniteurs ultra-larges (3440 x 1440)",
      li4: "32:9 - Super ultra-large (5120 x 1440)",
      li5: "4:3 - Ancien (1024 x 768), encore utilisé dans certaines tablettes",
      li6: "3:2 - Appareils Surface, certains Chromebooks (2256 x 1504)",
      heading4: "Choisir la bonne résolution",
      p1: "Pour la productivité générale, le QHD (2560 x 1440) sur un moniteur 27 pouces offre un excellent équilibre entre espace d'écran et clarté du texte à 109 PPI. Pour la retouche photo et vidéo, le 4K (3840 x 2160) fournit le détail nécessaire pour évaluer la qualité fine de l'image. Pour le jeu, la résolution doit correspondre à la capacité de votre GPU - 1080p pour les configurations économiques, 1440p pour le milieu de gamme et 4K pour les systèmes haut de gamme.",
      p2: "Vérifiez votre résolution d'affichage actuelle avec notre Vérificateur de Résolution d'Écran, ou calculez la densité de pixels avec le Calculateur de PPI.",
    },
  },
  de: {
    faq: [
      { question: "Was ist die häufigste Bildschirmauflösung?", answer: "Stand 2026 ist 1920 x 1080 (Full HD) weiterhin die weltweit häufigste Desktop-Auflösung, die von etwa 55 % der Desktop-Nutzer verwendet wird. 2560 x 1440 (QHD) ist die zweithäufigste mit etwa 15 %." },
      { question: "Was ist 4K-Auflösung in Pixeln?", answer: "4K (auch UHD genannt) ist 3840 x 2160 Pixel, genau die vierfache Pixelanzahl von Full HD (1920 x 1080). Cinema 4K (DCI 4K) ist etwas breiter mit 4096 x 2160 Pixel." },
      { question: "Ist QHD dasselbe wie 2K?", answer: "Nicht genau. QHD ist 2560 x 1440 Pixel. Echtes 2K (DCI 2K) ist 2048 x 1080 Pixel. QHD wird jedoch häufig (wenn auch ungenau) als '2K' vermarktet, weil seine horizontale Auflösung nahe bei 2560 liegt." },
      { question: "Wie viele Pixel hat 8K?", answer: "8K-Auflösung (7680 x 4320) enthält 33,2 Millionen Pixel - 16-mal so viele wie Full HD. 8K-Displays werden hauptsächlich für professionelle Videoproduktion und großformatige kommerzielle Displays eingesetzt." },
    ],
    body: {
      heading1: "Gängige Bildschirmauflösungen",
      tableHead1: "Name", tableHead2: "Auflösung (px)", tableHead3: "Seitenverhältnis", tableHead4: "Pixel gesamt",
      heading2: "Auflösungen nach Gerätetyp",
      heading2a: "Laptops",
      tableHead5: "Bildschirmgröße", tableHead6: "Gängige Auflösungen", tableHead7: "PPI-Bereich",
      heading2b: "Desktop-Monitore",
      heading3: "Gängige Seitenverhältnisse",
      li1: "16:9 - Standard-Breitbild (die meisten Monitore, TVs, Smartphones im Querformat)",
      li2: "16:10 - Üblich für Produktivitäts-Laptops (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Ultrawide-Monitore (3440 x 1440)",
      li4: "32:9 - Super Ultrawide (5120 x 1440)",
      li5: "4:3 - Altformat (1024 x 768), noch in einigen Tablets verwendet",
      li6: "3:2 - Surface-Geräte, einige Chromebooks (2256 x 1504)",
      heading4: "Die richtige Auflösung wählen",
      p1: "Für allgemeine Produktivität bietet QHD (2560 x 1440) auf einem 27-Zoll-Monitor ein ausgezeichnetes Gleichgewicht zwischen Bildschirmfläche und Textklarheit bei 109 PPI. Für Foto- und Videobearbeitung liefert 4K (3840 x 2160) die nötige Detailtiefe zur Beurteilung feiner Bildqualität. Für Gaming sollte die Auflösung zur GPU-Leistung passen - 1080p für Budget-Setups, 1440p für die Mittelklasse und 4K für High-End-Systeme.",
      p2: "Überprüfen Sie Ihre aktuelle Bildschirmauflösung mit unserem Bildschirmauflösungs-Checker oder berechnen Sie die Pixeldichte mit dem PPI-Rechner.",
    },
  },
  pt: {
    faq: [
      { question: "Qual a resolução de tela mais comum?", answer: "Em 2026, 1920 x 1080 (Full HD) continua sendo a resolução de desktop mais comum no mundo, usada por aproximadamente 55% dos usuários de desktop. 2560 x 1440 (QHD) é a segunda mais comum com cerca de 15%." },
      { question: "Qual é a resolução 4K em pixels?", answer: "4K (também chamado UHD) é 3840 x 2160 pixels, exatamente quatro vezes a contagem de pixels do Full HD (1920 x 1080). Cinema 4K (DCI 4K) é ligeiramente mais largo com 4096 x 2160 pixels." },
      { question: "QHD é o mesmo que 2K?", answer: "Não exatamente. QHD é 2560 x 1440 pixels. O verdadeiro 2K (DCI 2K) é 2048 x 1080 pixels. No entanto, QHD é comumente (embora imprecisamente) comercializado como '2K' porque sua resolução horizontal está próxima de 2560." },
      { question: "Quantos pixels tem 8K?", answer: "A resolução 8K (7680 x 4320) contém 33,2 milhões de pixels - 16 vezes a contagem de pixels do Full HD. Telas 8K são usadas principalmente para produção de vídeo profissional e displays comerciais de grande formato." },
    ],
    body: {
      heading1: "Resoluções de tela comuns",
      tableHead1: "Nome", tableHead2: "Resolução (px)", tableHead3: "Proporção", tableHead4: "Pixels totais",
      heading2: "Resoluções por tipo de dispositivo", heading2a: "Laptops",
      tableHead5: "Tamanho da tela", tableHead6: "Resoluções comuns", tableHead7: "Faixa PPI",
      heading2b: "Monitores de mesa",
      heading3: "Proporções comuns",
      li1: "16:9 - Widescreen padrão (maioria dos monitores, TVs, celulares em paisagem)",
      li2: "16:10 - Comum para laptops de produtividade (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Monitores ultrawide (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Legado (1024 x 768), ainda usado em alguns tablets",
      li6: "3:2 - Dispositivos Surface, alguns Chromebooks (2256 x 1504)",
      heading4: "Escolhendo a resolução certa",
      p1: "Para produtividade geral, QHD (2560 x 1440) em um monitor de 27 polegadas oferece um excelente equilíbrio entre espaço de tela e clareza de texto a 109 PPI. Para edição de fotos e vídeos, 4K (3840 x 2160) fornece o detalhe necessário para avaliar a qualidade fina da imagem. Para jogos, a resolução deve corresponder à capacidade da sua GPU - 1080p para configurações econômicas, 1440p para médio alcance e 4K para sistemas de ponta.",
      p2: "Verifique sua resolução de tela atual com nosso Verificador de Resolução de Tela, ou calcule a densidade de pixels com a Calculadora de PPI.",
    },
  },
  hi: {
    faq: [
      { question: "सबसे आम स्क्रीन रिज़ॉल्यूशन कौन सा है?", answer: "2026 तक, 1920 x 1080 (Full HD) दुनिया भर में सबसे आम डेस्कटॉप रिज़ॉल्यूशन बना हुआ है, जिसका उपयोग लगभग 55% डेस्कटॉप उपयोगकर्ता करते हैं। 2560 x 1440 (QHD) लगभग 15% के साथ दूसरा सबसे आम है।" },
      { question: "4K रिज़ॉल्यूशन पिक्सेल में कितना है?", answer: "4K (UHD भी कहा जाता है) 3840 x 2160 पिक्सेल है, Full HD (1920 x 1080) की पिक्सेल गणना का ठीक चार गुना। Cinema 4K (DCI 4K) 4096 x 2160 पिक्सेल पर थोड़ा चौड़ा है।" },
      { question: "क्या QHD और 2K एक ही हैं?", answer: "बिल्कुल नहीं। QHD 2560 x 1440 पिक्सेल है। सच्चा 2K (DCI 2K) 2048 x 1080 पिक्सेल है। हालांकि, QHD को आमतौर पर (गलत तरीके से) '2K' के रूप में विपणन किया जाता है क्योंकि इसका क्षैतिज रिज़ॉल्यूशन 2560 के करीब है।" },
      { question: "8K में कितने पिक्सेल होते हैं?", answer: "8K रिज़ॉल्यूशन (7680 x 4320) में 33.2 मिलियन पिक्सेल हैं - Full HD की पिक्सेल गणना का 16 गुना। 8K डिस्प्ले मुख्य रूप से पेशेवर वीडियो उत्पादन और बड़े प्रारूप वाणिज्यिक डिस्प्ले के लिए उपयोग किए जाते हैं।" },
    ],
    body: {
      heading1: "सामान्य डिस्प्ले रिज़ॉल्यूशन",
      tableHead1: "नाम", tableHead2: "रिज़ॉल्यूशन (px)", tableHead3: "आस्पेक्ट रेशियो", tableHead4: "कुल पिक्सेल",
      heading2: "डिवाइस प्रकार के अनुसार रिज़ॉल्यूशन", heading2a: "लैपटॉप",
      tableHead5: "स्क्रीन आकार", tableHead6: "सामान्य रिज़ॉल्यूशन", tableHead7: "PPI रेंज",
      heading2b: "डेस्कटॉप मॉनिटर",
      heading3: "सामान्य आस्पेक्ट रेशियो",
      li1: "16:9 - मानक वाइडस्क्रीन (अधिकांश मॉनिटर, TV, लैंडस्केप में फोन)",
      li2: "16:10 - प्रोडक्टिविटी लैपटॉप के लिए सामान्य (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - अल्ट्रावाइड मॉनिटर (3440 x 1440)",
      li4: "32:9 - सुपर अल्ट्रावाइड (5120 x 1440)",
      li5: "4:3 - लीगेसी (1024 x 768), अभी भी कुछ टैबलेट में उपयोग किया जाता है",
      li6: "3:2 - Surface डिवाइस, कुछ Chromebooks (2256 x 1504)",
      heading4: "सही रिज़ॉल्यूशन चुनना",
      p1: "सामान्य उत्पादकता के लिए, 27 इंच मॉनिटर पर QHD (2560 x 1440) 109 PPI पर स्क्रीन स्पेस और टेक्स्ट स्पष्टता का उत्कृष्ट संतुलन प्रदान करता है। फोटो और वीडियो एडिटिंग के लिए, 4K (3840 x 2160) बारीक इमेज गुणवत्ता का मूल्यांकन करने के लिए आवश्यक विवरण प्रदान करता है। गेमिंग के लिए, रिज़ॉल्यूशन आपकी GPU क्षमता से मेल खाना चाहिए - बजट सेटअप के लिए 1080p, मिड-रेंज के लिए 1440p, और हाई-एंड सिस्टम के लिए 4K।",
      p2: "हमारे स्क्रीन रिज़ॉल्यूशन चेकर से अपना वर्तमान डिस्प्ले रिज़ॉल्यूशन जांचें, या PPI कैलकुलेटर से पिक्सेल घनत्व की गणना करें।",
    },
  },
  ja: {
    faq: [
      { question: "最も一般的な画面解像度は？", answer: "2026年現在、1920 x 1080（Full HD）は世界で最も一般的なデスクトップ解像度で、約55%のデスクトップユーザーが使用しています。2560 x 1440（QHD）が約15%で2番目に一般的です。" },
      { question: "4K解像度はピクセルでいくつですか？", answer: "4K（UHDとも呼ばれる）は3840 x 2160ピクセルで、Full HD（1920 x 1080）のちょうど4倍のピクセル数です。Cinema 4K（DCI 4K）は4096 x 2160ピクセルとやや広いです。" },
      { question: "QHDと2Kは同じですか？", answer: "正確には違います。QHDは2560 x 1440ピクセルです。真の2K（DCI 2K）は2048 x 1080ピクセルです。ただし、QHDは水平解像度が2560に近いため、一般的に（不正確ですが）「2K」として販売されています。" },
      { question: "8Kには何ピクセルありますか？", answer: "8K解像度（7680 x 4320）は3320万ピクセルを含み、Full HDの16倍のピクセル数です。8Kディスプレイは主にプロの映像制作と大型商業ディスプレイに使用されています。" },
    ],
    body: {
      heading1: "一般的なディスプレイ解像度",
      tableHead1: "名称", tableHead2: "解像度 (px)", tableHead3: "アスペクト比", tableHead4: "総ピクセル数",
      heading2: "デバイスタイプ別解像度", heading2a: "ノートパソコン",
      tableHead5: "画面サイズ", tableHead6: "一般的な解像度", tableHead7: "PPI範囲",
      heading2b: "デスクトップモニター",
      heading3: "一般的なアスペクト比",
      li1: "16:9 - 標準ワイドスクリーン（ほとんどのモニター、TV、横向きのスマートフォン）",
      li2: "16:10 - 生産性ノートPC向け（1920 x 1200、2560 x 1600）",
      li3: "21:9 - ウルトラワイドモニター（3440 x 1440）",
      li4: "32:9 - スーパーウルトラワイド（5120 x 1440）",
      li5: "4:3 - レガシー（1024 x 768）、一部のタブレットで使用",
      li6: "3:2 - Surfaceデバイス、一部のChromebook（2256 x 1504）",
      heading4: "適切な解像度の選び方",
      p1: "一般的な生産性には、27インチモニターのQHD（2560 x 1440）が109 PPIで画面スペースとテキストの明瞭さの優れたバランスを提供します。写真・動画編集には、4K（3840 x 2160）が細かい画質の評価に必要なディテールを提供します。ゲームでは、解像度はGPU性能に合わせるべきです - 予算セットアップには1080p、ミドルレンジには1440p、ハイエンドシステムには4K。",
      p2: "スクリーン解像度チェッカーで現在のディスプレイ解像度を確認するか、PPIカリキュレーターでピクセル密度を計算してください。",
    },
  },
  ko: {
    faq: [
      { question: "가장 일반적인 화면 해상도는?", answer: "2026년 기준, 1920 x 1080(Full HD)이 전 세계에서 가장 일반적인 데스크톱 해상도로, 약 55%의 데스크톱 사용자가 사용합니다. 2560 x 1440(QHD)이 약 15%로 두 번째입니다." },
      { question: "4K 해상도는 몇 픽셀인가요?", answer: "4K(UHD라고도 함)는 3840 x 2160 픽셀로, Full HD(1920 x 1080)의 정확히 4배 픽셀 수입니다. Cinema 4K(DCI 4K)는 4096 x 2160 픽셀로 약간 더 넓습니다." },
      { question: "QHD와 2K는 같은 건가요?", answer: "정확히는 아닙니다. QHD는 2560 x 1440 픽셀입니다. 진정한 2K(DCI 2K)는 2048 x 1080 픽셀입니다. 하지만 QHD는 수평 해상도가 2560에 가깝기 때문에 흔히 (부정확하게) '2K'로 마케팅됩니다." },
      { question: "8K는 몇 픽셀인가요?", answer: "8K 해상도(7680 x 4320)는 3320만 픽셀로 Full HD의 16배입니다. 8K 디스플레이는 주로 전문 영상 제작과 대형 상업용 디스플레이에 사용됩니다." },
    ],
    body: {
      heading1: "일반적인 디스플레이 해상도",
      tableHead1: "이름", tableHead2: "해상도 (px)", tableHead3: "화면비", tableHead4: "총 픽셀",
      heading2: "기기 유형별 해상도", heading2a: "노트북",
      tableHead5: "화면 크기", tableHead6: "일반 해상도", tableHead7: "PPI 범위",
      heading2b: "데스크톱 모니터",
      heading3: "일반적인 화면비",
      li1: "16:9 - 표준 와이드스크린(대부분의 모니터, TV, 가로 모드 폰)",
      li2: "16:10 - 생산성 노트북에 일반적(1920 x 1200, 2560 x 1600)",
      li3: "21:9 - 울트라와이드 모니터(3440 x 1440)",
      li4: "32:9 - 슈퍼 울트라와이드(5120 x 1440)",
      li5: "4:3 - 레거시(1024 x 768), 일부 태블릿에서 사용",
      li6: "3:2 - Surface 기기, 일부 Chromebook(2256 x 1504)",
      heading4: "적합한 해상도 선택",
      p1: "일반 생산성의 경우, 27인치 모니터에서 QHD(2560 x 1440)는 109 PPI로 화면 공간과 텍스트 선명도의 우수한 균형을 제공합니다. 사진 및 비디오 편집의 경우, 4K(3840 x 2160)는 세밀한 이미지 품질 평가에 필요한 디테일을 제공합니다. 게임의 경우, 해상도는 GPU 성능에 맞아야 합니다 - 저가 설정에 1080p, 중간급에 1440p, 고급 시스템에 4K.",
      p2: "화면 해상도 검사기로 현재 디스플레이 해상도를 확인하거나 PPI 계산기로 픽셀 밀도를 계산하세요.",
    },
  },
  it: {
    faq: [
      { question: "Qual e la risoluzione dello schermo piu comune?", answer: "Nel 2026, 1920 x 1080 (Full HD) rimane la risoluzione desktop piu comune al mondo, usata da circa il 55% degli utenti desktop. 2560 x 1440 (QHD) e la seconda piu comune con circa il 15%." },
      { question: "Qual e la risoluzione 4K in pixel?", answer: "4K (anche chiamato UHD) e 3840 x 2160 pixel, esattamente quattro volte il conteggio pixel del Full HD (1920 x 1080). Cinema 4K (DCI 4K) e leggermente piu largo a 4096 x 2160 pixel." },
      { question: "QHD e uguale a 2K?", answer: "Non esattamente. QHD e 2560 x 1440 pixel. Il vero 2K (DCI 2K) e 2048 x 1080 pixel. Tuttavia, QHD e comunemente (se imprecisamente) commercializzato come '2K' perche la sua risoluzione orizzontale e vicina a 2560." },
      { question: "Quanti pixel ha l'8K?", answer: "La risoluzione 8K (7680 x 4320) contiene 33,2 milioni di pixel - 16 volte il conteggio pixel del Full HD. I display 8K sono usati principalmente per la produzione video professionale e display commerciali di grande formato." },
    ],
    body: {
      heading1: "Risoluzioni display comuni",
      tableHead1: "Nome", tableHead2: "Risoluzione (px)", tableHead3: "Rapporto", tableHead4: "Pixel totali",
      heading2: "Risoluzioni per tipo di dispositivo", heading2a: "Laptop",
      tableHead5: "Dimensione schermo", tableHead6: "Risoluzioni comuni", tableHead7: "Range PPI",
      heading2b: "Monitor desktop",
      heading3: "Rapporti d'aspetto comuni",
      li1: "16:9 - Widescreen standard (la maggior parte dei monitor, TV, telefoni in orizzontale)",
      li2: "16:10 - Comune per laptop di produttivita (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Monitor ultrawide (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Legacy (1024 x 768), ancora usato in alcuni tablet",
      li6: "3:2 - Dispositivi Surface, alcuni Chromebook (2256 x 1504)",
      heading4: "Scegliere la risoluzione giusta",
      p1: "Per la produttivita generale, QHD (2560 x 1440) su un monitor da 27 pollici offre un eccellente equilibrio tra spazio sullo schermo e nitidezza del testo a 109 PPI. Per il fotoritocco e il montaggio video, 4K (3840 x 2160) fornisce il dettaglio necessario per valutare la qualita fine dell'immagine. Per il gaming, la risoluzione dovrebbe corrispondere alla capacita della GPU - 1080p per configurazioni economiche, 1440p per fascia media e 4K per sistemi di fascia alta.",
      p2: "Controlla la tua attuale risoluzione dello schermo con il nostro Verificatore di Risoluzione Schermo, o calcola la densita di pixel con il Calcolatore PPI.",
    },
  },
  nl: {
    faq: [
      { question: "Wat is de meest voorkomende schermresolutie?", answer: "In 2026 is 1920 x 1080 (Full HD) nog steeds de meest voorkomende desktopresolutie wereldwijd, gebruikt door ongeveer 55% van de desktopgebruikers. 2560 x 1440 (QHD) is de op een na meest voorkomende met ongeveer 15%." },
      { question: "Wat is 4K-resolutie in pixels?", answer: "4K (ook UHD genoemd) is 3840 x 2160 pixels, precies vier keer het aantal pixels van Full HD (1920 x 1080). Cinema 4K (DCI 4K) is iets breder met 4096 x 2160 pixels." },
      { question: "Is QHD hetzelfde als 2K?", answer: "Niet precies. QHD is 2560 x 1440 pixels. Echt 2K (DCI 2K) is 2048 x 1080 pixels. QHD wordt echter vaak (maar onnauwkeurig) als '2K' op de markt gebracht omdat de horizontale resolutie dicht bij 2560 ligt." },
      { question: "Hoeveel pixels heeft 8K?", answer: "8K-resolutie (7680 x 4320) bevat 33,2 miljoen pixels - 16 keer het aantal pixels van Full HD. 8K-displays worden voornamelijk gebruikt voor professionele videoproductie en grootformaat commerciele displays." },
    ],
    body: {
      heading1: "Veelvoorkomende schermresoluties",
      tableHead1: "Naam", tableHead2: "Resolutie (px)", tableHead3: "Beeldverhouding", tableHead4: "Totaal pixels",
      heading2: "Resoluties per apparaattype", heading2a: "Laptops",
      tableHead5: "Schermformaat", tableHead6: "Veelvoorkomende resoluties", tableHead7: "PPI-bereik",
      heading2b: "Desktopmonitoren",
      heading3: "Veelvoorkomende beeldverhoudingen",
      li1: "16:9 - Standaard breedbeeld (de meeste monitoren, TV's, telefoons in landschap)",
      li2: "16:10 - Gebruikelijk voor productiviteitslaptops (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Ultrawide monitoren (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Legacy (1024 x 768), nog steeds gebruikt in sommige tablets",
      li6: "3:2 - Surface-apparaten, sommige Chromebooks (2256 x 1504)",
      heading4: "De juiste resolutie kiezen",
      p1: "Voor algemene productiviteit biedt QHD (2560 x 1440) op een 27-inch monitor een uitstekende balans tussen schermruimte en teksthelderheid bij 109 PPI. Voor foto- en videobewerking levert 4K (3840 x 2160) het detail dat nodig is om fijne beeldkwaliteit te beoordelen. Voor gaming moet de resolutie overeenkomen met je GPU-capaciteit - 1080p voor budgetopstellingen, 1440p voor middenklasse en 4K voor high-end systemen.",
      p2: "Controleer je huidige schermresolutie met onze Schermresolutie Checker, of bereken de pixeldichtheid met de PPI-calculator.",
    },
  },
  ar: {
    faq: [
      { question: "ما هي دقة الشاشة الأكثر شيوعًا؟", answer: "في 2026، لا تزال 1920 x 1080 (Full HD) أكثر دقة سطح المكتب شيوعًا في العالم، يستخدمها حوالي 55% من مستخدمي سطح المكتب. 2560 x 1440 (QHD) هي الثانية الأكثر شيوعًا بحوالي 15%." },
      { question: "ما هي دقة 4K بالبكسل؟", answer: "4K (تسمى أيضًا UHD) هي 3840 x 2160 بكسل، أربعة أضعاف عدد بكسلات Full HD (1920 x 1080) بالضبط. Cinema 4K (DCI 4K) أعرض قليلاً بدقة 4096 x 2160 بكسل." },
      { question: "هل QHD هو نفسه 2K؟", answer: "ليس بالضبط. QHD هو 2560 x 1440 بكسل. 2K الحقيقي (DCI 2K) هو 2048 x 1080 بكسل. ومع ذلك، يتم تسويق QHD عادة (وإن كان بشكل غير دقيق) باسم '2K' لأن دقته الأفقية قريبة من 2560." },
      { question: "كم عدد البكسلات في 8K؟", answer: "دقة 8K (7680 x 4320) تحتوي على 33.2 مليون بكسل - 16 ضعف عدد بكسلات Full HD. تُستخدم شاشات 8K بشكل أساسي لإنتاج الفيديو الاحترافي وشاشات العرض التجارية الكبيرة." },
    ],
    body: {
      heading1: "دقات العرض الشائعة",
      tableHead1: "الاسم", tableHead2: "الدقة (بكسل)", tableHead3: "نسبة العرض", tableHead4: "إجمالي البكسلات",
      heading2: "الدقات حسب نوع الجهاز", heading2a: "أجهزة الكمبيوتر المحمولة",
      tableHead5: "حجم الشاشة", tableHead6: "الدقات الشائعة", tableHead7: "نطاق PPI",
      heading2b: "شاشات سطح المكتب",
      heading3: "نسب العرض الشائعة",
      li1: "16:9 - شاشة عريضة قياسية (معظم الشاشات، التلفزيونات، الهواتف في الوضع الأفقي)",
      li2: "16:10 - شائعة لأجهزة الكمبيوتر المحمولة الإنتاجية (1920 x 1200، 2560 x 1600)",
      li3: "21:9 - شاشات فائقة العرض (3440 x 1440)",
      li4: "32:9 - شاشات فائقة العرض جدًا (5120 x 1440)",
      li5: "4:3 - قديم (1024 x 768)، لا يزال مستخدمًا في بعض الأجهزة اللوحية",
      li6: "3:2 - أجهزة Surface، بعض Chromebooks (2256 x 1504)",
      heading4: "اختيار الدقة المناسبة",
      p1: "للإنتاجية العامة، QHD (2560 x 1440) على شاشة 27 بوصة يوفر توازنًا ممتازًا بين مساحة الشاشة ووضوح النص عند 109 PPI. لتحرير الصور والفيديو، 4K (3840 x 2160) يوفر التفاصيل اللازمة لتقييم جودة الصورة الدقيقة. للألعاب، يجب أن تتوافق الدقة مع قدرة GPU - 1080p للإعدادات الاقتصادية، 1440p للمتوسطة، و 4K للأنظمة المتطورة.",
      p2: "تحقق من دقة شاشتك الحالية باستخدام أداة فحص دقة الشاشة، أو احسب كثافة البكسل باستخدام حاسبة PPI.",
    },
  },
  tr: {
    faq: [
      { question: "En yaygın ekran çözünürlüğü nedir?", answer: "2026 itibarıyla, 1920 x 1080 (Full HD) dünya çapında en yaygın masaüstü çözünürlüğü olmaya devam ediyor ve masaüstü kullanıcılarının yaklaşık %55'i tarafından kullanılıyor. 2560 x 1440 (QHD) yaklaşık %15 ile ikinci sırada." },
      { question: "4K çözünürlük piksel olarak nedir?", answer: "4K (UHD olarak da bilinir) 3840 x 2160 pikseldir, Full HD'nin (1920 x 1080) tam dört katı piksel sayısına sahiptir. Cinema 4K (DCI 4K) 4096 x 2160 piksel ile biraz daha geniştir." },
      { question: "QHD ile 2K aynı mı?", answer: "Tam olarak değil. QHD 2560 x 1440 pikseldir. Gerçek 2K (DCI 2K) 2048 x 1080 pikseldir. Ancak QHD, yatay çözünürlüğü 2560'a yakın olduğu için yaygın olarak (yanlış da olsa) '2K' olarak pazarlanır." },
      { question: "8K kaç pikseldir?", answer: "8K çözünürlük (7680 x 4320) 33,2 milyon piksel içerir - Full HD'nin 16 katı. 8K ekranlar ağırlıklı olarak profesyonel video prodüksiyonu ve büyük format ticari ekranlar için kullanılır." },
    ],
    body: {
      heading1: "Yaygın ekran çözünürlükleri",
      tableHead1: "Ad", tableHead2: "Çözünürlük (px)", tableHead3: "En-Boy Oranı", tableHead4: "Toplam Piksel",
      heading2: "Cihaz türüne göre çözünürlükler", heading2a: "Dizüstü bilgisayarlar",
      tableHead5: "Ekran Boyutu", tableHead6: "Yaygın Çözünürlükler", tableHead7: "PPI Aralığı",
      heading2b: "Masaüstü monitörler",
      heading3: "Yaygın en-boy oranları",
      li1: "16:9 - Standart geniş ekran (çoğu monitör, TV, yatay konumda telefonlar)",
      li2: "16:10 - Verimlilik dizüstü bilgisayarları için yaygın (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Ultra geniş monitörler (3440 x 1440)",
      li4: "32:9 - Süper ultra geniş (5120 x 1440)",
      li5: "4:3 - Eski (1024 x 768), hâlâ bazı tabletlerde kullanılıyor",
      li6: "3:2 - Surface cihazları, bazı Chromebook'lar (2256 x 1504)",
      heading4: "Doğru çözünürlüğü seçmek",
      p1: "Genel verimlilik için 27 inç monitörde QHD (2560 x 1440), 109 PPI'de ekran alanı ve metin netliği arasında mükemmel bir denge sunar. Fotoğraf ve video düzenleme için 4K (3840 x 2160), ince görüntü kalitesini değerlendirmek için gereken ayrıntıyı sağlar. Oyun için çözünürlük GPU kapasitenizle eşleşmelidir - bütçe kurulumları için 1080p, orta segment için 1440p ve üst düzey sistemler için 4K.",
      p2: "Ekran Çözünürlüğü Denetleyicimizle mevcut ekran çözünürlüğünüzü kontrol edin veya PPI Hesaplayıcı ile piksel yoğunluğunu hesaplayın.",
    },
  },
  pl: {
    faq: [
      { question: "Jaka jest najczęstsza rozdzielczość ekranu?", answer: "W 2026 roku 1920 x 1080 (Full HD) pozostaje najczęstszą rozdzielczością pulpitu na świecie, używaną przez około 55% użytkowników komputerów stacjonarnych. 2560 x 1440 (QHD) jest drugą najczęstszą z około 15%." },
      { question: "Ile pikseli ma rozdzielczość 4K?", answer: "4K (również nazywane UHD) to 3840 x 2160 pikseli, dokładnie czterokrotność liczby pikseli Full HD (1920 x 1080). Cinema 4K (DCI 4K) jest nieco szersza - 4096 x 2160 pikseli." },
      { question: "Czy QHD to to samo co 2K?", answer: "Nie do końca. QHD to 2560 x 1440 pikseli. Prawdziwe 2K (DCI 2K) to 2048 x 1080 pikseli. QHD jest jednak powszechnie (choć niedokładnie) reklamowane jako '2K', ponieważ jego rozdzielczość pozioma jest bliska 2560." },
      { question: "Ile pikseli ma 8K?", answer: "Rozdzielczość 8K (7680 x 4320) zawiera 33,2 miliona pikseli - 16 razy więcej niż Full HD. Ekrany 8K są używane głównie do profesjonalnej produkcji wideo i wielkoformatowych wyświetlaczy komercyjnych." },
    ],
    body: {
      heading1: "Popularne rozdzielczości wyświetlaczy",
      tableHead1: "Nazwa", tableHead2: "Rozdzielczość (px)", tableHead3: "Proporcje", tableHead4: "Łączna liczba pikseli",
      heading2: "Rozdzielczości według typu urządzenia", heading2a: "Laptopy",
      tableHead5: "Rozmiar ekranu", tableHead6: "Popularne rozdzielczości", tableHead7: "Zakres PPI",
      heading2b: "Monitory biurkowe",
      heading3: "Popularne proporcje ekranu",
      li1: "16:9 - Standardowy panoramiczny (większość monitorów, TV, telefony w orientacji poziomej)",
      li2: "16:10 - Typowy dla laptopów biurowych (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Monitory ultrawide (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Starszy format (1024 x 768), wciąż używany w niektórych tabletach",
      li6: "3:2 - Urządzenia Surface, niektóre Chromebooki (2256 x 1504)",
      heading4: "Wybór odpowiedniej rozdzielczości",
      p1: "Do ogólnej produktywności QHD (2560 x 1440) na monitorze 27-calowym oferuje doskonałą równowagę między przestrzenią ekranową a czytelnością tekstu przy 109 PPI. Do edycji zdjęć i wideo 4K (3840 x 2160) zapewnia szczegółowość potrzebną do oceny jakości obrazu. Do gier rozdzielczość powinna odpowiadać możliwościom GPU - 1080p dla budżetowych konfiguracji, 1440p dla średniej klasy i 4K dla systemów najwyższej klasy.",
      p2: "Sprawdź swoją obecną rozdzielczość ekranu za pomocą naszego Sprawdzacza Rozdzielczości Ekranu lub oblicz gęstość pikseli za pomocą Kalkulatora PPI.",
    },
  },
  id: {
    faq: [
      { question: "Apa resolusi layar paling umum?", answer: "Pada 2026, 1920 x 1080 (Full HD) tetap menjadi resolusi desktop paling umum di dunia, digunakan oleh sekitar 55% pengguna desktop. 2560 x 1440 (QHD) adalah yang paling umum kedua dengan sekitar 15%." },
      { question: "Berapa resolusi 4K dalam piksel?", answer: "4K (juga disebut UHD) adalah 3840 x 2160 piksel, tepat empat kali jumlah piksel Full HD (1920 x 1080). Cinema 4K (DCI 4K) sedikit lebih lebar yaitu 4096 x 2160 piksel." },
      { question: "Apakah QHD sama dengan 2K?", answer: "Tidak tepat. QHD adalah 2560 x 1440 piksel. 2K sesungguhnya (DCI 2K) adalah 2048 x 1080 piksel. Namun, QHD umumnya (meskipun tidak akurat) dipasarkan sebagai '2K' karena resolusi horizontalnya mendekati 2560." },
      { question: "Berapa piksel pada 8K?", answer: "Resolusi 8K (7680 x 4320) berisi 33,2 juta piksel - 16 kali jumlah piksel Full HD. Layar 8K terutama digunakan untuk produksi video profesional dan layar komersial format besar." },
    ],
    body: {
      heading1: "Resolusi tampilan umum",
      tableHead1: "Nama", tableHead2: "Resolusi (px)", tableHead3: "Rasio Aspek", tableHead4: "Total Piksel",
      heading2: "Resolusi berdasarkan jenis perangkat", heading2a: "Laptop",
      tableHead5: "Ukuran Layar", tableHead6: "Resolusi Umum", tableHead7: "Rentang PPI",
      heading2b: "Monitor desktop",
      heading3: "Rasio aspek umum",
      li1: "16:9 - Layar lebar standar (sebagian besar monitor, TV, ponsel dalam posisi lanskap)",
      li2: "16:10 - Umum untuk laptop produktivitas (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Monitor ultrawide (3440 x 1440)",
      li4: "32:9 - Super ultrawide (5120 x 1440)",
      li5: "4:3 - Lama (1024 x 768), masih digunakan di beberapa tablet",
      li6: "3:2 - Perangkat Surface, beberapa Chromebook (2256 x 1504)",
      heading4: "Memilih resolusi yang tepat",
      p1: "Untuk produktivitas umum, QHD (2560 x 1440) pada monitor 27 inci menawarkan keseimbangan yang sangat baik antara ruang layar dan kejelasan teks pada 109 PPI. Untuk pengeditan foto dan video, 4K (3840 x 2160) memberikan detail yang diperlukan untuk mengevaluasi kualitas gambar halus. Untuk gaming, resolusi harus sesuai dengan kemampuan GPU - 1080p untuk setup hemat, 1440p untuk menengah, dan 4K untuk sistem kelas atas.",
      p2: "Periksa resolusi tampilan Anda saat ini dengan Pemeriksa Resolusi Layar kami, atau hitung kepadatan piksel dengan Kalkulator PPI.",
    },
  },
  ru: {
    faq: [
      { question: "Какое разрешение экрана самое распространённое?", answer: "В 2026 году 1920 x 1080 (Full HD) остаётся самым распространённым разрешением настольных мониторов в мире, его используют около 55% пользователей. 2560 x 1440 (QHD) занимает второе место с примерно 15%." },
      { question: "Какое разрешение 4K в пикселях?", answer: "4K (также UHD) - это 3840 x 2160 пикселей, ровно в четыре раза больше пикселей, чем Full HD (1920 x 1080). Cinema 4K (DCI 4K) немного шире - 4096 x 2160 пикселей." },
      { question: "QHD - это то же самое, что 2K?", answer: "Не совсем. QHD - это 2560 x 1440 пикселей. Настоящее 2K (DCI 2K) - 2048 x 1080 пикселей. Однако QHD часто (хотя и неточно) продаётся как '2K', поскольку его горизонтальное разрешение близко к 2560." },
      { question: "Сколько пикселей в 8K?", answer: "Разрешение 8K (7680 x 4320) содержит 33,2 миллиона пикселей - в 16 раз больше, чем Full HD. 8K-дисплеи в основном используются для профессионального видеопроизводства и крупноформатных коммерческих экранов." },
    ],
    body: {
      heading1: "Распространённые разрешения дисплеев",
      tableHead1: "Название", tableHead2: "Разрешение (пикс.)", tableHead3: "Соотношение сторон", tableHead4: "Всего пикселей",
      heading2: "Разрешения по типу устройства", heading2a: "Ноутбуки",
      tableHead5: "Размер экрана", tableHead6: "Распространённые разрешения", tableHead7: "Диапазон PPI",
      heading2b: "Настольные мониторы",
      heading3: "Распространённые соотношения сторон",
      li1: "16:9 - Стандартный широкоформатный (большинство мониторов, ТВ, телефоны в альбомной ориентации)",
      li2: "16:10 - Распространён для рабочих ноутбуков (1920 x 1200, 2560 x 1600)",
      li3: "21:9 - Сверхширокие мониторы (3440 x 1440)",
      li4: "32:9 - Сверхсверхширокие (5120 x 1440)",
      li5: "4:3 - Устаревший (1024 x 768), всё ещё используется в некоторых планшетах",
      li6: "3:2 - Устройства Surface, некоторые Chromebook (2256 x 1504)",
      heading4: "Выбор подходящего разрешения",
      p1: "Для общей продуктивности QHD (2560 x 1440) на 27-дюймовом мониторе обеспечивает отличный баланс между рабочим пространством и чёткостью текста при 109 PPI. Для редактирования фото и видео 4K (3840 x 2160) обеспечивает детализацию, необходимую для оценки качества изображения. Для игр разрешение должно соответствовать возможностям GPU - 1080p для бюджетных сборок, 1440p для среднего класса и 4K для топовых систем.",
      p2: "Проверьте текущее разрешение экрана с помощью нашего Проверщика разрешения экрана или рассчитайте плотность пикселей с помощью Калькулятора PPI.",
    },
  },
};
