import type { PageContentMap } from "./types";

export const content: PageContentMap = {
  en: {
    faq: [
      {
        question: "Can I use DPI and PPI interchangeably?",
        answer:
          "In casual use, many people swap the terms. However, DPI technically applies to printers (ink dots per inch), while PPI applies to screens and digital images (pixels per inch). Using the correct term avoids ambiguity in professional settings.",
      },
      {
        question: "Is 300 DPI the same as 300 PPI?",
        answer:
          "When referring to an image file, '300 DPI' usually means 300 PPI — the image has 300 pixels per inch at its intended print size. The printer's actual DPI (often 720-2880) determines how finely those pixels are reproduced with ink dots.",
      },
      {
        question: "Which matters more for web design, DPI or PPI?",
        answer:
          "Neither. Web browsers ignore the DPI/PPI metadata in image files. Only pixel dimensions matter for web display. A 1200x800 image renders the same on screen regardless of its DPI setting.",
      },
      {
        question: "Why do image editors default to 72 or 96 DPI?",
        answer:
          "72 DPI was the legacy Mac screen resolution, and 96 DPI is the Windows default. These defaults have no impact on how the image appears on screen — they only affect the default print size calculation.",
      },
    ],
    body: {
      heading1: "Quick Answer",
      p1: "DPI (dots per inch) is a printer metric. It measures how many tiny ink dots a printer deposits per inch. PPI (pixels per inch) is a screen and image metric. It measures how many pixels are packed into each inch of a display or digital file. Both describe density per inch, but they apply to different contexts.",
      heading2: "Side-by-Side Comparison",
      th1: "Attribute",
      th2: "DPI (Dots Per Inch)",
      th3: "PPI (Pixels Per Inch)",
      td1_1: "Stands for",
      td1_2: "Dots per inch",
      td1_3: "Pixels per inch",
      td2_1: "Applies to",
      td2_2: "Printers and printing",
      td2_3: "Screens and digital images",
      td3_1: "Measures",
      td3_2: "Ink dot density",
      td3_3: "Pixel density",
      td4_1: "Typical values",
      td4_2: "600–2880 (printers)",
      td4_3: "72–460 (screens)",
      td5_1: "Higher value means",
      td5_2: "Smoother, finer prints",
      td5_3: "Sharper, crisper display",
      td6_1: "Controlled by",
      td6_2: "Printer hardware/driver",
      td6_3: "Display hardware",
      td7_1: "Affects file size?",
      td7_2: "No (metadata only)",
      td7_3: "No (metadata only)",
      heading3: "When DPI Applies",
      p2: "DPI is relevant when you are printing. Your printer's DPI setting determines how finely it can reproduce the image data. A 1200 DPI laser printer can lay down ink dots much more precisely than a 300 DPI printer, producing smoother gradients and finer text.",
      p3: "When someone says \"save this image at 300 DPI,\" they usually mean 300 PPI — they want 300 pixels per inch at the intended print size. The printer's actual DPI is a separate hardware specification.",
      heading4: "When PPI Applies",
      p4: "PPI is relevant for screens and image files. Your monitor has a fixed PPI determined by its resolution and physical size. When preparing images for a specific print size, PPI tells you how many pixels you need. At 300 PPI, a 10x8-inch print requires a 3000x2400 pixel image.",
      heading5: "Common Confusion",
      p5: "The confusion arises because software like Photoshop labels image resolution as \"DPI\" even though it is technically PPI. The image file stores pixels, not dots. The dots only exist when the image is printed. In practice, understanding that pixel dimensions are what matter — for both screen and print — resolves most confusion.",
      p6: "Use our DPI Calculator to determine print dimensions, or the PPI Calculator to find the pixel density of any screen.",
    },
  },
  es: {
    faq: [
      {
        question: "¿Puedo usar DPI y PPI indistintamente?",
        answer:
          "En uso casual, muchas personas intercambian los términos. Sin embargo, DPI técnicamente se aplica a impresoras (puntos de tinta por pulgada), mientras que PPI se aplica a pantallas e imágenes digitales (píxeles por pulgada). Usar el término correcto evita ambigüedades en entornos profesionales.",
      },
      {
        question: "¿Es lo mismo 300 DPI que 300 PPI?",
        answer:
          "Al referirse a un archivo de imagen, '300 DPI' generalmente significa 300 PPI — la imagen tiene 300 píxeles por pulgada en su tamaño de impresión previsto. El DPI real de la impresora (a menudo 720-2880) determina con qué finura se reproducen esos píxeles con puntos de tinta.",
      },
      {
        question: "¿Qué importa más para el diseño web, DPI o PPI?",
        answer:
          "Ninguno. Los navegadores web ignoran los metadatos de DPI/PPI en los archivos de imagen. Solo las dimensiones en píxeles importan para la visualización web. Una imagen de 1200x800 se renderiza igual en pantalla independientemente de su configuración de DPI.",
      },
      {
        question: "¿Por qué los editores de imagen usan 72 o 96 DPI por defecto?",
        answer:
          "72 DPI era la resolución de pantalla heredada de Mac, y 96 DPI es el valor predeterminado de Windows. Estos valores predeterminados no afectan cómo la imagen aparece en pantalla — solo afectan el cálculo del tamaño de impresión predeterminado.",
      },
    ],
    body: {
      heading1: "Respuesta rápida",
      p1: "DPI (puntos por pulgada) es una métrica de impresora. Mide cuántos pequeños puntos de tinta deposita una impresora por pulgada. PPI (píxeles por pulgada) es una métrica de pantalla e imagen. Mide cuántos píxeles están empaquetados en cada pulgada de una pantalla o archivo digital. Ambos describen densidad por pulgada, pero se aplican a contextos diferentes.",
      heading2: "Comparación lado a lado",
      th1: "Atributo",
      th2: "DPI (Puntos por pulgada)",
      th3: "PPI (Píxeles por pulgada)",
      td1_1: "Significa",
      td1_2: "Puntos por pulgada",
      td1_3: "Píxeles por pulgada",
      td2_1: "Se aplica a",
      td2_2: "Impresoras e impresión",
      td2_3: "Pantallas e imágenes digitales",
      td3_1: "Mide",
      td3_2: "Densidad de puntos de tinta",
      td3_3: "Densidad de píxeles",
      td4_1: "Valores típicos",
      td4_2: "600–2880 (impresoras)",
      td4_3: "72–460 (pantallas)",
      td5_1: "Mayor valor significa",
      td5_2: "Impresiones más suaves y finas",
      td5_3: "Pantalla más nítida y clara",
      td6_1: "Controlado por",
      td6_2: "Hardware/controlador de impresora",
      td6_3: "Hardware de pantalla",
      td7_1: "¿Afecta el tamaño del archivo?",
      td7_2: "No (solo metadatos)",
      td7_3: "No (solo metadatos)",
      heading3: "Cuándo se aplica DPI",
      p2: "DPI es relevante cuando estás imprimiendo. La configuración DPI de tu impresora determina con qué finura puede reproducir los datos de imagen. Una impresora láser de 1200 DPI puede depositar puntos de tinta con mucha más precisión que una impresora de 300 DPI, produciendo gradientes más suaves y texto más fino.",
      p3: "Cuando alguien dice \"guardar esta imagen a 300 DPI\", generalmente quiere decir 300 PPI — quiere 300 píxeles por pulgada en el tamaño de impresión previsto. El DPI real de la impresora es una especificación de hardware separada.",
      heading4: "Cuándo se aplica PPI",
      p4: "PPI es relevante para pantallas y archivos de imagen. Tu monitor tiene un PPI fijo determinado por su resolución y tamaño físico. Al preparar imágenes para un tamaño de impresión específico, el PPI te indica cuántos píxeles necesitas. A 300 PPI, una impresión de 10x8 pulgadas requiere una imagen de 3000x2400 píxeles.",
      heading5: "Confusión común",
      p5: "La confusión surge porque software como Photoshop etiqueta la resolución de imagen como \"DPI\" aunque técnicamente es PPI. El archivo de imagen almacena píxeles, no puntos. Los puntos solo existen cuando la imagen se imprime. En la práctica, entender que las dimensiones en píxeles son lo que importa — tanto para pantalla como para impresión — resuelve la mayor parte de la confusión.",
      p6: "Usa nuestra Calculadora de DPI para determinar dimensiones de impresión, o la Calculadora de PPI para encontrar la densidad de píxeles de cualquier pantalla.",
    },
  },
  fr: {
    faq: [
      {
        question: "Peut-on utiliser DPI et PPI de manière interchangeable ?",
        answer:
          "Dans l'usage courant, beaucoup de gens échangent les termes. Cependant, DPI s'applique techniquement aux imprimantes (points d'encre par pouce), tandis que PPI s'applique aux écrans et images numériques (pixels par pouce). Utiliser le bon terme évite l'ambiguïté dans les milieux professionnels.",
      },
      {
        question: "300 DPI est-il identique à 300 PPI ?",
        answer:
          "Lorsqu'on parle d'un fichier image, '300 DPI' signifie généralement 300 PPI — l'image a 300 pixels par pouce à sa taille d'impression prévue. Le DPI réel de l'imprimante (souvent 720-2880) détermine avec quelle finesse ces pixels sont reproduits avec des points d'encre.",
      },
      {
        question: "Qu'est-ce qui compte le plus pour le design web, DPI ou PPI ?",
        answer:
          "Ni l'un ni l'autre. Les navigateurs web ignorent les métadonnées DPI/PPI dans les fichiers image. Seules les dimensions en pixels comptent pour l'affichage web. Une image 1200x800 s'affiche de la même façon à l'écran quel que soit son réglage DPI.",
      },
      {
        question: "Pourquoi les éditeurs d'images utilisent-ils 72 ou 96 DPI par défaut ?",
        answer:
          "72 DPI était la résolution d'écran historique du Mac, et 96 DPI est la valeur par défaut de Windows. Ces valeurs n'ont aucun impact sur l'affichage de l'image à l'écran — elles n'affectent que le calcul de la taille d'impression par défaut.",
      },
    ],
    body: {
      heading1: "Réponse rapide",
      p1: "DPI (points par pouce) est une métrique d'imprimante. Il mesure combien de petits points d'encre une imprimante dépose par pouce. PPI (pixels par pouce) est une métrique d'écran et d'image. Il mesure combien de pixels sont concentrés dans chaque pouce d'un écran ou fichier numérique. Les deux décrivent la densité par pouce, mais s'appliquent à des contextes différents.",
      heading2: "Comparaison côte à côte",
      th1: "Attribut",
      th2: "DPI (Points par pouce)",
      th3: "PPI (Pixels par pouce)",
      td1_1: "Signifie",
      td1_2: "Points par pouce",
      td1_3: "Pixels par pouce",
      td2_1: "S'applique à",
      td2_2: "Imprimantes et impression",
      td2_3: "Écrans et images numériques",
      td3_1: "Mesure",
      td3_2: "Densité de points d'encre",
      td3_3: "Densité de pixels",
      td4_1: "Valeurs typiques",
      td4_2: "600–2880 (imprimantes)",
      td4_3: "72–460 (écrans)",
      td5_1: "Valeur plus élevée signifie",
      td5_2: "Impressions plus lisses et fines",
      td5_3: "Affichage plus net et clair",
      td6_1: "Contrôlé par",
      td6_2: "Matériel/pilote d'imprimante",
      td6_3: "Matériel d'affichage",
      td7_1: "Affecte la taille du fichier ?",
      td7_2: "Non (métadonnées uniquement)",
      td7_3: "Non (métadonnées uniquement)",
      heading3: "Quand DPI s'applique",
      p2: "Le DPI est pertinent lorsque vous imprimez. Le réglage DPI de votre imprimante détermine avec quelle finesse elle peut reproduire les données de l'image. Une imprimante laser 1200 DPI peut déposer des points d'encre beaucoup plus précisément qu'une imprimante 300 DPI, produisant des dégradés plus lisses et un texte plus fin.",
      p3: "Quand quelqu'un dit « enregistrer cette image à 300 DPI », il veut généralement dire 300 PPI — il veut 300 pixels par pouce à la taille d'impression prévue. Le DPI réel de l'imprimante est une spécification matérielle distincte.",
      heading4: "Quand PPI s'applique",
      p4: "Le PPI est pertinent pour les écrans et les fichiers image. Votre moniteur a un PPI fixe déterminé par sa résolution et sa taille physique. Lors de la préparation d'images pour une taille d'impression spécifique, le PPI vous indique combien de pixels vous avez besoin. À 300 PPI, une impression 10x8 pouces nécessite une image de 3000x2400 pixels.",
      heading5: "Confusion courante",
      p5: "La confusion vient du fait que des logiciels comme Photoshop étiquettent la résolution d'image comme « DPI » alors que c'est techniquement du PPI. Le fichier image stocke des pixels, pas des points. Les points n'existent que lorsque l'image est imprimée. En pratique, comprendre que les dimensions en pixels sont ce qui compte — pour l'écran comme pour l'impression — résout la majeure partie de la confusion.",
      p6: "Utilisez notre Calculateur DPI pour déterminer les dimensions d'impression, ou le Calculateur PPI pour trouver la densité de pixels de n'importe quel écran.",
    },
  },
  de: {
    faq: [
      {
        question: "Kann ich DPI und PPI austauschbar verwenden?",
        answer:
          "Im allgemeinen Sprachgebrauch verwechseln viele Menschen die Begriffe. Technisch gesehen bezieht sich DPI jedoch auf Drucker (Tintenpunkte pro Zoll), während PPI auf Bildschirme und digitale Bilder (Pixel pro Zoll) zutrifft. Die Verwendung des richtigen Begriffs vermeidet Mehrdeutigkeit im professionellen Umfeld.",
      },
      {
        question: "Sind 300 DPI dasselbe wie 300 PPI?",
        answer:
          "Bei Bilddateien bedeutet '300 DPI' normalerweise 300 PPI — das Bild hat 300 Pixel pro Zoll bei der vorgesehenen Druckgröße. Der tatsächliche DPI des Druckers (oft 720-2880) bestimmt, wie fein diese Pixel mit Tintenpunkten reproduziert werden.",
      },
      {
        question: "Was ist wichtiger für Webdesign, DPI oder PPI?",
        answer:
          "Keines von beiden. Webbrowser ignorieren die DPI/PPI-Metadaten in Bilddateien. Nur die Pixelmaße zählen für die Webdarstellung. Ein 1200x800-Bild wird auf dem Bildschirm gleich angezeigt, unabhängig von seiner DPI-Einstellung.",
      },
      {
        question: "Warum verwenden Bildeditoren standardmäßig 72 oder 96 DPI?",
        answer:
          "72 DPI war die historische Mac-Bildschirmauflösung, und 96 DPI ist der Windows-Standard. Diese Standardwerte haben keinen Einfluss darauf, wie das Bild auf dem Bildschirm erscheint — sie beeinflussen nur die Berechnung der Standard-Druckgröße.",
      },
    ],
    body: {
      heading1: "Schnelle Antwort",
      p1: "DPI (Punkte pro Zoll) ist eine Druckermetrik. Es misst, wie viele winzige Tintenpunkte ein Drucker pro Zoll aufträgt. PPI (Pixel pro Zoll) ist eine Bildschirm- und Bildmetrik. Es misst, wie viele Pixel in jedem Zoll eines Displays oder einer Digitaldatei gepackt sind. Beide beschreiben die Dichte pro Zoll, gelten aber für unterschiedliche Kontexte.",
      heading2: "Vergleich nebeneinander",
      th1: "Attribut",
      th2: "DPI (Punkte pro Zoll)",
      th3: "PPI (Pixel pro Zoll)",
      td1_1: "Steht für",
      td1_2: "Punkte pro Zoll",
      td1_3: "Pixel pro Zoll",
      td2_1: "Gilt für",
      td2_2: "Drucker und Druck",
      td2_3: "Bildschirme und digitale Bilder",
      td3_1: "Misst",
      td3_2: "Tintenpunktdichte",
      td3_3: "Pixeldichte",
      td4_1: "Typische Werte",
      td4_2: "600–2880 (Drucker)",
      td4_3: "72–460 (Bildschirme)",
      td5_1: "Höherer Wert bedeutet",
      td5_2: "Glattere, feinere Drucke",
      td5_3: "Schärfere, klarere Anzeige",
      td6_1: "Gesteuert durch",
      td6_2: "Drucker-Hardware/-Treiber",
      td6_3: "Display-Hardware",
      td7_1: "Beeinflusst Dateigröße?",
      td7_2: "Nein (nur Metadaten)",
      td7_3: "Nein (nur Metadaten)",
      heading3: "Wann DPI relevant ist",
      p2: "DPI ist relevant beim Drucken. Die DPI-Einstellung Ihres Druckers bestimmt, wie fein er die Bilddaten reproduzieren kann. Ein 1200-DPI-Laserdrucker kann Tintenpunkte viel präziser aufbringen als ein 300-DPI-Drucker und erzeugt so glattere Verläufe und feineren Text.",
      p3: "Wenn jemand sagt „dieses Bild bei 300 DPI speichern“, meint er normalerweise 300 PPI — er möchte 300 Pixel pro Zoll bei der vorgesehenen Druckgröße. Der tatsächliche DPI des Druckers ist eine separate Hardware-Spezifikation.",
      heading4: "Wann PPI relevant ist",
      p4: "PPI ist relevant für Bildschirme und Bilddateien. Ihr Monitor hat einen festen PPI, der durch seine Auflösung und physische Größe bestimmt wird. Bei der Vorbereitung von Bildern für eine bestimmte Druckgröße sagt Ihnen PPI, wie viele Pixel Sie brauchen. Bei 300 PPI benötigt ein 10x8-Zoll-Druck ein 3000x2400-Pixel-Bild.",
      heading5: "Häufige Verwirrung",
      p5: "Die Verwirrung entsteht, weil Software wie Photoshop die Bildauflösung als „DPI“ bezeichnet, obwohl es technisch PPI ist. Die Bilddatei speichert Pixel, keine Punkte. Die Punkte existieren erst, wenn das Bild gedruckt wird. In der Praxis löst das Verständnis, dass Pixelmaße das Entscheidende sind — sowohl für Bildschirm als auch für Druck — die meiste Verwirrung.",
      p6: "Verwenden Sie unseren DPI-Rechner zur Bestimmung der Druckdimensionen oder den PPI-Rechner zur Ermittlung der Pixeldichte jedes Bildschirms.",
    },
  },
  pt: {
    faq: [
      {
        question: "Posso usar DPI e PPI de forma intercambiável?",
        answer:
          "No uso casual, muitas pessoas trocam os termos. No entanto, DPI tecnicamente se aplica a impressoras (pontos de tinta por polegada), enquanto PPI se aplica a telas e imagens digitais (pixels por polegada). Usar o termo correto evita ambiguidade em ambientes profissionais.",
      },
      {
        question: "300 DPI é o mesmo que 300 PPI?",
        answer:
          "Ao se referir a um arquivo de imagem, '300 DPI' geralmente significa 300 PPI — a imagem tem 300 pixels por polegada no tamanho de impressão pretendido. O DPI real da impressora (frequentemente 720-2880) determina com que fineza esses pixels são reproduzidos com pontos de tinta.",
      },
      {
        question: "O que importa mais para web design, DPI ou PPI?",
        answer:
          "Nenhum dos dois. Os navegadores web ignoram os metadados DPI/PPI nos arquivos de imagem. Apenas as dimensões em pixels importam para exibição na web. Uma imagem 1200x800 é renderizada da mesma forma na tela independente da configuração de DPI.",
      },
      {
        question: "Por que editores de imagem usam 72 ou 96 DPI como padrão?",
        answer:
          "72 DPI era a resolução de tela legada do Mac, e 96 DPI é o padrão do Windows. Esses padrões não têm impacto em como a imagem aparece na tela — afetam apenas o cálculo do tamanho de impressão padrão.",
      },
    ],
    body: {
      heading1: "Resposta rápida",
      p1: "DPI (pontos por polegada) é uma métrica de impressora. Mede quantos pequenos pontos de tinta uma impressora deposita por polegada. PPI (pixels por polegada) é uma métrica de tela e imagem. Mede quantos pixels estão compactados em cada polegada de uma tela ou arquivo digital. Ambos descrevem densidade por polegada, mas se aplicam a contextos diferentes.",
      heading2: "Comparação lado a lado",
      th1: "Atributo",
      th2: "DPI (Pontos por polegada)",
      th3: "PPI (Pixels por polegada)",
      td1_1: "Significa",
      td1_2: "Pontos por polegada",
      td1_3: "Pixels por polegada",
      td2_1: "Aplica-se a",
      td2_2: "Impressoras e impressão",
      td2_3: "Telas e imagens digitais",
      td3_1: "Mede",
      td3_2: "Densidade de pontos de tinta",
      td3_3: "Densidade de pixels",
      td4_1: "Valores típicos",
      td4_2: "600–2880 (impressoras)",
      td4_3: "72–460 (telas)",
      td5_1: "Valor mais alto significa",
      td5_2: "Impressões mais suaves e finas",
      td5_3: "Exibição mais nítida e clara",
      td6_1: "Controlado por",
      td6_2: "Hardware/driver da impressora",
      td6_3: "Hardware da tela",
      td7_1: "Afeta tamanho do arquivo?",
      td7_2: "Não (apenas metadados)",
      td7_3: "Não (apenas metadados)",
      heading3: "Quando DPI se aplica",
      p2: "DPI é relevante quando você está imprimindo. A configuração de DPI da sua impressora determina com que fineza ela pode reproduzir os dados da imagem. Uma impressora laser de 1200 DPI pode depositar pontos de tinta com muito mais precisão do que uma de 300 DPI, produzindo gradientes mais suaves e texto mais fino.",
      p3: "Quando alguém diz \"salvar esta imagem a 300 DPI\", geralmente quer dizer 300 PPI — quer 300 pixels por polegada no tamanho de impressão pretendido. O DPI real da impressora é uma especificação de hardware separada.",
      heading4: "Quando PPI se aplica",
      p4: "PPI é relevante para telas e arquivos de imagem. Seu monitor tem um PPI fixo determinado por sua resolução e tamanho físico. Ao preparar imagens para um tamanho de impressão específico, o PPI indica quantos pixels você precisa. A 300 PPI, uma impressão de 10x8 polegadas requer uma imagem de 3000x2400 pixels.",
      heading5: "Confusão comum",
      p5: "A confusão surge porque softwares como o Photoshop rotulam a resolução da imagem como \"DPI\" mesmo sendo tecnicamente PPI. O arquivo de imagem armazena pixels, não pontos. Os pontos só existem quando a imagem é impressa. Na prática, entender que as dimensões em pixels são o que importa — tanto para tela quanto para impressão — resolve a maior parte da confusão.",
      p6: "Use nossa Calculadora de DPI para determinar dimensões de impressão, ou a Calculadora de PPI para encontrar a densidade de pixels de qualquer tela.",
    },
  },
  hi: {
    faq: [
      { question: "क्या मैं DPI और PPI को एक दूसरे की जगह उपयोग कर सकता हूं?", answer: "सामान्य उपयोग में, बहुत से लोग इन शब्दों को अदल-बदल कर इस्तेमाल करते हैं। हालांकि, DPI तकनीकी रूप से प्रिंटर (प्रति इंच स्याही के डॉट) पर लागू होता है, जबकि PPI स्क्रीन और डिजिटल इमेज (प्रति इंच पिक्सेल) पर लागू होता है। सही शब्द का उपयोग पेशेवर सेटिंग में अस्पष्टता से बचाता है।" },
      { question: "क्या 300 DPI और 300 PPI एक ही है?", answer: "इमेज फ़ाइल के संदर्भ में, '300 DPI' का आमतौर पर मतलब 300 PPI होता है — इमेज के इच्छित प्रिंट आकार पर 300 पिक्सेल प्रति इंच। प्रिंटर का वास्तविक DPI (अक्सर 720-2880) यह निर्धारित करता है कि उन पिक्सेल को स्याही के डॉट से कितनी बारीकी से पुनर्उत्पादित किया जाता है।" },
      { question: "वेब डिज़ाइन के लिए DPI या PPI में से कौन अधिक महत्वपूर्ण है?", answer: "कोई भी नहीं। वेब ब्राउज़र इमेज फ़ाइलों में DPI/PPI मेटाडेटा को अनदेखा करते हैं। वेब डिस्प्ले के लिए केवल पिक्सेल आयाम मायने रखते हैं। 1200x800 की इमेज DPI सेटिंग की परवाह किए बिना स्क्रीन पर समान रेंडर होती है।" },
      { question: "इमेज एडिटर डिफ़ॉल्ट रूप से 72 या 96 DPI क्यों उपयोग करते हैं?", answer: "72 DPI Mac की विरासत स्क्रीन रिज़ॉल्यूशन थी, और 96 DPI Windows का डिफ़ॉल्ट है। ये डिफ़ॉल्ट इमेज के स्क्रीन पर दिखने के तरीके को प्रभावित नहीं करते — ये केवल डिफ़ॉल्ट प्रिंट आकार गणना को प्रभावित करते हैं।" },
    ],
    body: {
      heading1: "त्वरित उत्तर",
      p1: "DPI (डॉट्स प्रति इंच) एक प्रिंटर मेट्रिक है। यह मापता है कि प्रिंटर प्रति इंच कितने छोटे स्याही के डॉट जमा करता है। PPI (पिक्सेल प्रति इंच) एक स्क्रीन और इमेज मेट्रिक है। यह मापता है कि डिस्प्ले या डिजिटल फ़ाइल के प्रत्येक इंच में कितने पिक्सेल भरे हुए हैं। दोनों प्रति इंच घनत्व का वर्णन करते हैं, लेकिन वे अलग-अलग संदर्भों पर लागू होते हैं।",
      heading2: "आमने-सामने तुलना",
      th1: "विशेषता", th2: "DPI (डॉट्स प्रति इंच)", th3: "PPI (पिक्सेल प्रति इंच)",
      td1_1: "मतलब", td1_2: "डॉट्स प्रति इंच", td1_3: "पिक्सेल प्रति इंच",
      td2_1: "लागू होता है", td2_2: "प्रिंटर और प्रिंटिंग", td2_3: "स्क्रीन और डिजिटल इमेज",
      td3_1: "मापता है", td3_2: "स्याही डॉट घनत्व", td3_3: "पिक्सेल घनत्व",
      td4_1: "विशिष्ट मान", td4_2: "600–2880 (प्रिंटर)", td4_3: "72–460 (स्क्रीन)",
      td5_1: "उच्च मान का अर्थ", td5_2: "चिकने, बारीक प्रिंट", td5_3: "तीक्ष्ण, स्पष्ट डिस्प्ले",
      td6_1: "नियंत्रित करता है", td6_2: "प्रिंटर हार्डवेयर/ड्राइवर", td6_3: "डिस्प्ले हार्डवेयर",
      td7_1: "फ़ाइल आकार प्रभावित करता है?", td7_2: "नहीं (केवल मेटाडेटा)", td7_3: "नहीं (केवल मेटाडेटा)",
      heading3: "DPI कब लागू होता है",
      p2: "DPI प्रिंटिंग के समय प्रासंगिक है। आपके प्रिंटर की DPI सेटिंग निर्धारित करती है कि वह इमेज डेटा को कितनी बारीकी से पुनर्उत्पादित कर सकता है। 1200 DPI लेजर प्रिंटर 300 DPI प्रिंटर की तुलना में बहुत अधिक सटीकता से स्याही के डॉट रख सकता है, जो चिकने ग्रेडिएंट और बारीक टेक्स्ट उत्पन्न करता है।",
      p3: "जब कोई कहता है \"इस इमेज को 300 DPI पर सेव करें\", उनका आमतौर पर मतलब 300 PPI होता है — वे इच्छित प्रिंट आकार पर 300 पिक्सेल प्रति इंच चाहते हैं। प्रिंटर का वास्तविक DPI एक अलग हार्डवेयर विनिर्देश है।",
      heading4: "PPI कब लागू होता है",
      p4: "PPI स्क्रीन और इमेज फ़ाइलों के लिए प्रासंगिक है। आपके मॉनिटर का PPI उसके रिज़ॉल्यूशन और भौतिक आकार द्वारा निर्धारित होता है। किसी विशिष्ट प्रिंट आकार के लिए इमेज तैयार करते समय, PPI आपको बताता है कि आपको कितने पिक्सेल चाहिए। 300 PPI पर, 10x8 इंच प्रिंट के लिए 3000x2400 पिक्सेल की इमेज चाहिए।",
      heading5: "सामान्य भ्रम",
      p5: "भ्रम इसलिए उत्पन्न होता है क्योंकि Photoshop जैसे सॉफ़्टवेयर इमेज रिज़ॉल्यूशन को \"DPI\" लेबल करते हैं जबकि तकनीकी रूप से यह PPI है। इमेज फ़ाइल पिक्सेल संग्रहीत करती है, डॉट नहीं। डॉट केवल तब मौजूद होते हैं जब इमेज प्रिंट होती है। व्यवहार में, यह समझना कि पिक्सेल आयाम ही महत्वपूर्ण हैं — स्क्रीन और प्रिंट दोनों के लिए — अधिकांश भ्रम को हल करता है।",
      p6: "प्रिंट आयाम निर्धारित करने के लिए हमारे DPI कैलकुलेटर का उपयोग करें, या किसी भी स्क्रीन की पिक्सेल घनत्व ज्ञात करने के लिए PPI कैलकुलेटर का उपयोग करें।",
    },
  },
  ja: {
    faq: [
      { question: "DPIとPPIは同じ意味で使えますか？", answer: "カジュアルな使用では、多くの人がこれらの用語を入れ替えて使います。しかし、DPIは技術的にはプリンター（インチあたりのインクドット数）に適用され、PPIはスクリーンとデジタル画像（インチあたりのピクセル数）に適用されます。正しい用語を使うことで、プロの現場での曖昧さを避けられます。" },
      { question: "300 DPIと300 PPIは同じですか？", answer: "画像ファイルを指す場合、「300 DPI」は通常300 PPI を意味します — 意図した印刷サイズで1インチあたり300ピクセルです。プリンターの実際のDPI（多くの場合720〜2880）は、それらのピクセルがインクドットでどれだけ精密に再現されるかを決定します。" },
      { question: "Webデザインで重要なのはDPIとPPIのどちらですか？", answer: "どちらでもありません。WebブラウザはImage ファイルのDPI/PPIメタデータを無視します。Web表示にはピクセル寸法のみが重要です。1200x800の画像はDPI設定に関係なく画面上で同じようにレンダリングされます。" },
      { question: "なぜ画像エディタは72または96 DPIをデフォルトにしているのですか？", answer: "72 DPIはMacのレガシー画面解像度で、96 DPIはWindowsのデフォルトです。これらのデフォルト値は画像の画面表示に影響しません — デフォルトの印刷サイズ計算にのみ影響します。" },
    ],
    body: {
      heading1: "クイックアンサー",
      p1: "DPI（ドット・パー・インチ）はプリンターの指標です。プリンターがインチあたりに配置する小さなインクドットの数を測定します。PPI（ピクセル・パー・インチ）はスクリーンと画像の指標です。ディスプレイやデジタルファイルの各インチにどれだけのピクセルが詰まっているかを測定します。どちらもインチあたりの密度を表しますが、異なるコンテキストに適用されます。",
      heading2: "比較表",
      th1: "属性", th2: "DPI（ドット・パー・インチ）", th3: "PPI（ピクセル・パー・インチ）",
      td1_1: "意味", td1_2: "インチあたりのドット数", td1_3: "インチあたりのピクセル数",
      td2_1: "適用対象", td2_2: "プリンターと印刷", td2_3: "スクリーンとデジタル画像",
      td3_1: "測定対象", td3_2: "インクドット密度", td3_3: "ピクセル密度",
      td4_1: "一般的な値", td4_2: "600〜2880（プリンター）", td4_3: "72〜460（スクリーン）",
      td5_1: "高い値は", td5_2: "より滑らかで精密な印刷", td5_3: "より鮮明でクリアな表示",
      td6_1: "制御元", td6_2: "プリンターハードウェア/ドライバー", td6_3: "ディスプレイハードウェア",
      td7_1: "ファイルサイズに影響？", td7_2: "いいえ（メタデータのみ）", td7_3: "いいえ（メタデータのみ）",
      heading3: "DPIが適用される場面",
      p2: "DPIは印刷時に関連します。プリンターのDPI設定は、画像データをどれだけ精密に再現できるかを決定します。1200 DPIレーザープリンターは300 DPIプリンターよりもはるかに正確にインクドットを配置でき、より滑らかなグラデーションと精密なテキストを生成します。",
      p3: "「この画像を300 DPIで保存して」と言う場合、通常は300 PPIを意味します — 意図した印刷サイズでインチあたり300ピクセルが欲しいということです。プリンターの実際のDPIは別のハードウェア仕様です。",
      heading4: "PPIが適用される場面",
      p4: "PPIはスクリーンと画像ファイルに関連します。モニターには解像度と物理サイズによって決まる固定のPPIがあります。特定の印刷サイズのために画像を準備する際、PPIは必要なピクセル数を教えてくれます。300 PPIでは、10×8インチの印刷には3000×2400ピクセルの画像が必要です。",
      heading5: "よくある混同",
      p5: "混同が生じるのは、Photoshopのようなソフトウェアが画像解像度を技術的にはPPIであるにもかかわらず「DPI」とラベル付けしているためです。画像ファイルはピクセルを保存し、ドットではありません。ドットは画像が印刷されたときにのみ存在します。実際には、スクリーンでも印刷でもピクセル寸法が重要であるということを理解すれば、ほとんどの混同は解消されます。",
      p6: "印刷寸法を決定するにはDPI計算機を、任意のスクリーンのピクセル密度を調べるにはPPI計算機をご利用ください。",
    },
  },
  ko: {
    faq: [
      { question: "DPI와 PPI를 서로 바꿔서 사용할 수 있나요?", answer: "일상적인 사용에서 많은 사람들이 이 용어를 혼용합니다. 그러나 DPI는 기술적으로 프린터(인치당 잉크 도트 수)에 적용되며, PPI는 화면과 디지털 이미지(인치당 픽셀 수)에 적용됩니다. 올바른 용어를 사용하면 전문 환경에서 모호함을 피할 수 있습니다." },
      { question: "300 DPI는 300 PPI와 같은 건가요?", answer: "이미지 파일을 말할 때, '300 DPI'는 보통 300 PPI를 의미합니다 - 의도된 인쇄 크기에서 인치당 300 픽셀입니다. 프린터의 실제 DPI(보통 720-2880)는 그 픽셀들이 잉크 도트로 얼마나 정밀하게 재현되는지를 결정합니다." },
      { question: "웹 디자인에서 DPI와 PPI 중 어느 것이 더 중요한가요?", answer: "어느 것도 아닙니다. 웹 브라우저는 이미지 파일의 DPI/PPI 메타데이터를 무시합니다. 웹 표시에는 픽셀 크기만 중요합니다. 1200x800 이미지는 DPI 설정에 관계없이 화면에 동일하게 렌더링됩니다." },
      { question: "이미지 편집기가 기본적으로 72 또는 96 DPI를 사용하는 이유는?", answer: "72 DPI는 Mac의 레거시 화면 해상도였고 96 DPI는 Windows 기본값입니다. 이 기본값들은 이미지가 화면에 표시되는 방식에 영향을 미치지 않습니다 - 기본 인쇄 크기 계산에만 영향을 줍니다." },
    ],
    body: {
      heading1: "빠른 답변",
      p1: "DPI(인치당 도트 수)는 프린터 지표입니다. 프린터가 인치당 배치하는 작은 잉크 도트 수를 측정합니다. PPI(인치당 픽셀 수)는 화면 및 이미지 지표입니다. 디스플레이나 디지털 파일의 각 인치에 얼마나 많은 픽셀이 밀집되어 있는지를 측정합니다. 둘 다 인치당 밀도를 나타내지만 서로 다른 맥락에 적용됩니다.",
      heading2: "나란히 비교",
      th1: "속성", th2: "DPI (인치당 도트 수)", th3: "PPI (인치당 픽셀 수)",
      td1_1: "의미", td1_2: "인치당 도트 수", td1_3: "인치당 픽셀 수",
      td2_1: "적용 대상", td2_2: "프린터 및 인쇄", td2_3: "화면 및 디지털 이미지",
      td3_1: "측정 대상", td3_2: "잉크 도트 밀도", td3_3: "픽셀 밀도",
      td4_1: "일반적인 값", td4_2: "600–2880 (프린터)", td4_3: "72–460 (화면)",
      td5_1: "높은 값의 의미", td5_2: "더 부드럽고 정밀한 인쇄", td5_3: "더 선명하고 깨끗한 디스플레이",
      td6_1: "제어 주체", td6_2: "프린터 하드웨어/드라이버", td6_3: "디스플레이 하드웨어",
      td7_1: "파일 크기에 영향?", td7_2: "아니오 (메타데이터만)", td7_3: "아니오 (메타데이터만)",
      heading3: "DPI가 적용되는 경우",
      p2: "DPI는 인쇄할 때 관련됩니다. 프린터의 DPI 설정은 이미지 데이터를 얼마나 정밀하게 재현할 수 있는지를 결정합니다. 1200 DPI 레이저 프린터는 300 DPI 프린터보다 훨씬 정밀하게 잉크 도트를 배치하여 더 부드러운 그라데이션과 정밀한 텍스트를 생성합니다.",
      p3: "\"이 이미지를 300 DPI로 저장하세요\"라고 할 때, 보통 300 PPI를 의미합니다 - 의도된 인쇄 크기에서 인치당 300 픽셀을 원한다는 뜻입니다. 프린터의 실제 DPI는 별도의 하드웨어 사양입니다.",
      heading4: "PPI가 적용되는 경우",
      p4: "PPI는 화면과 이미지 파일에 관련됩니다. 모니터에는 해상도와 물리적 크기에 의해 결정되는 고정 PPI가 있습니다. 특정 인쇄 크기용 이미지를 준비할 때, PPI는 필요한 픽셀 수를 알려줍니다. 300 PPI에서 10x8인치 인쇄물에는 3000x2400 픽셀 이미지가 필요합니다.",
      heading5: "흔한 혼동",
      p5: "혼동은 Photoshop과 같은 소프트웨어가 이미지 해상도를 기술적으로는 PPI임에도 \"DPI\"로 표시하기 때문에 발생합니다. 이미지 파일은 픽셀을 저장하며 도트가 아닙니다. 도트는 이미지가 인쇄될 때만 존재합니다. 실제로, 화면과 인쇄 모두에서 픽셀 크기가 중요하다는 것을 이해하면 대부분의 혼동이 해결됩니다.",
      p6: "인쇄 크기를 결정하려면 DPI 계산기를, 화면의 픽셀 밀도를 알아보려면 PPI 계산기를 사용하세요.",
    },
  },
  it: {
    faq: [
      { question: "Posso usare DPI e PPI in modo intercambiabile?", answer: "Nell'uso comune, molte persone scambiano i termini. Tuttavia, DPI tecnicamente si applica alle stampanti (punti d'inchiostro per pollice), mentre PPI si applica a schermi e immagini digitali (pixel per pollice). Usare il termine corretto evita ambiguità in contesti professionali." },
      { question: "300 DPI è uguale a 300 PPI?", answer: "Riferendosi a un file immagine, '300 DPI' di solito significa 300 PPI — l'immagine ha 300 pixel per pollice alla dimensione di stampa prevista. Il DPI effettivo della stampante (spesso 720-2880) determina con quanta precisione quei pixel vengono riprodotti con punti d'inchiostro." },
      { question: "Cosa conta di più per il web design, DPI o PPI?", answer: "Nessuno dei due. I browser web ignorano i metadati DPI/PPI nei file immagine. Solo le dimensioni in pixel contano per la visualizzazione web. Un'immagine 1200x800 viene renderizzata allo stesso modo sullo schermo indipendentemente dalla sua impostazione DPI." },
      { question: "Perché gli editor di immagini usano 72 o 96 DPI come predefinito?", answer: "72 DPI era la risoluzione dello schermo legacy del Mac, e 96 DPI è il valore predefinito di Windows. Questi valori predefiniti non influenzano come l'immagine appare sullo schermo — influenzano solo il calcolo predefinito della dimensione di stampa." },
    ],
    body: {
      heading1: "Risposta rapida",
      p1: "DPI (punti per pollice) è una metrica della stampante. Misura quanti piccoli punti d'inchiostro una stampante deposita per pollice. PPI (pixel per pollice) è una metrica di schermo e immagine. Misura quanti pixel sono contenuti in ogni pollice di un display o file digitale. Entrambi descrivono la densità per pollice, ma si applicano a contesti diversi.",
      heading2: "Confronto affiancato",
      th1: "Attributo", th2: "DPI (Punti per pollice)", th3: "PPI (Pixel per pollice)",
      td1_1: "Significa", td1_2: "Punti per pollice", td1_3: "Pixel per pollice",
      td2_1: "Si applica a", td2_2: "Stampanti e stampa", td2_3: "Schermi e immagini digitali",
      td3_1: "Misura", td3_2: "Densità punti d'inchiostro", td3_3: "Densità pixel",
      td4_1: "Valori tipici", td4_2: "600–2880 (stampanti)", td4_3: "72–460 (schermi)",
      td5_1: "Valore più alto significa", td5_2: "Stampe più lisce e fini", td5_3: "Display più nitido e chiaro",
      td6_1: "Controllato da", td6_2: "Hardware/driver stampante", td6_3: "Hardware display",
      td7_1: "Influisce sulla dimensione del file?", td7_2: "No (solo metadati)", td7_3: "No (solo metadati)",
      heading3: "Quando si applica il DPI",
      p2: "Il DPI è rilevante quando si stampa. L'impostazione DPI della stampante determina con quanta precisione può riprodurre i dati dell'immagine. Una stampante laser a 1200 DPI può depositare punti d'inchiostro molto più precisamente di una a 300 DPI, producendo sfumature più lisce e testo più fine.",
      p3: "Quando qualcuno dice \"salvare questa immagine a 300 DPI\", di solito intende 300 PPI — vuole 300 pixel per pollice alla dimensione di stampa prevista. Il DPI effettivo della stampante è una specifica hardware separata.",
      heading4: "Quando si applica il PPI",
      p4: "Il PPI è rilevante per schermi e file immagine. Il monitor ha un PPI fisso determinato dalla sua risoluzione e dimensione fisica. Quando si preparano immagini per una dimensione di stampa specifica, il PPI indica quanti pixel servono. A 300 PPI, una stampa 10x8 pollici richiede un'immagine di 3000x2400 pixel.",
      heading5: "Confusione comune",
      p5: "La confusione nasce perché software come Photoshop etichettano la risoluzione dell'immagine come \"DPI\" anche se tecnicamente è PPI. Il file immagine memorizza pixel, non punti. I punti esistono solo quando l'immagine viene stampata. In pratica, capire che le dimensioni in pixel sono ciò che conta — sia per lo schermo che per la stampa — risolve la maggior parte della confusione.",
      p6: "Usa il nostro Calcolatore DPI per determinare le dimensioni di stampa, o il Calcolatore PPI per trovare la densità di pixel di qualsiasi schermo.",
    },
  },
  nl: {
    faq: [
      { question: "Kan ik DPI en PPI door elkaar gebruiken?", answer: "In informeel gebruik wisselen veel mensen de termen. Technisch gezien is DPI echter van toepassing op printers (inktpunten per inch), terwijl PPI van toepassing is op schermen en digitale afbeeldingen (pixels per inch). Het juiste begrip gebruiken voorkomt dubbelzinnigheid in professionele omgevingen." },
      { question: "Is 300 DPI hetzelfde als 300 PPI?", answer: "Bij een afbeeldingsbestand betekent '300 DPI' meestal 300 PPI — de afbeelding heeft 300 pixels per inch bij het beoogde afdrukformaat. De werkelijke DPI van de printer (vaak 720-2880) bepaalt hoe fijn die pixels worden gereproduceerd met inktpunten." },
      { question: "Wat is belangrijker voor webdesign, DPI of PPI?", answer: "Geen van beide. Webbrowsers negeren de DPI/PPI-metadata in afbeeldingsbestanden. Alleen pixelafmetingen zijn van belang voor webweergave. Een 1200x800 afbeelding wordt hetzelfde weergegeven op het scherm ongeacht de DPI-instelling." },
      { question: "Waarom gebruiken beeldbewerkingsprogramma's standaard 72 of 96 DPI?", answer: "72 DPI was de historische Mac-schermresolutie en 96 DPI is de Windows-standaard. Deze standaardwaarden hebben geen invloed op hoe de afbeelding op het scherm verschijnt — ze beïnvloeden alleen de standaard afdrukformaatberekening." },
    ],
    body: {
      heading1: "Snel antwoord",
      p1: "DPI (dots per inch) is een printermetriek. Het meet hoeveel kleine inktpunten een printer per inch aanbrengt. PPI (pixels per inch) is een scherm- en afbeeldingsmetriek. Het meet hoeveel pixels er in elke inch van een display of digitaal bestand zitten. Beide beschrijven dichtheid per inch, maar ze zijn van toepassing op verschillende contexten.",
      heading2: "Vergelijking naast elkaar",
      th1: "Kenmerk", th2: "DPI (Dots per inch)", th3: "PPI (Pixels per inch)",
      td1_1: "Staat voor", td1_2: "Punten per inch", td1_3: "Pixels per inch",
      td2_1: "Van toepassing op", td2_2: "Printers en afdrukken", td2_3: "Schermen en digitale afbeeldingen",
      td3_1: "Meet", td3_2: "Inktpuntdichtheid", td3_3: "Pixeldichtheid",
      td4_1: "Typische waarden", td4_2: "600–2880 (printers)", td4_3: "72–460 (schermen)",
      td5_1: "Hogere waarde betekent", td5_2: "Vloeiendere, fijnere afdrukken", td5_3: "Scherper, helderder display",
      td6_1: "Bestuurd door", td6_2: "Printerhardware/-driver", td6_3: "Displayhardware",
      td7_1: "Beïnvloedt bestandsgrootte?", td7_2: "Nee (alleen metadata)", td7_3: "Nee (alleen metadata)",
      heading3: "Wanneer DPI van toepassing is",
      p2: "DPI is relevant bij het afdrukken. De DPI-instelling van uw printer bepaalt hoe fijn deze de beeldgegevens kan reproduceren. Een 1200 DPI laserprinter kan inktpunten veel nauwkeuriger aanbrengen dan een 300 DPI printer, wat vloeiendere verlopen en fijner tekst oplevert.",
      p3: "Wanneer iemand zegt \"sla deze afbeelding op bij 300 DPI\", bedoelen ze meestal 300 PPI — ze willen 300 pixels per inch bij het beoogde afdrukformaat. De werkelijke DPI van de printer is een aparte hardwarespecificatie.",
      heading4: "Wanneer PPI van toepassing is",
      p4: "PPI is relevant voor schermen en afbeeldingsbestanden. Uw monitor heeft een vaste PPI bepaald door de resolutie en fysieke grootte. Bij het voorbereiden van afbeeldingen voor een specifiek afdrukformaat vertelt PPI u hoeveel pixels u nodig heeft. Bij 300 PPI vereist een afdruk van 10x8 inch een afbeelding van 3000x2400 pixels.",
      heading5: "Veelvoorkomende verwarring",
      p5: "De verwarring ontstaat doordat software zoals Photoshop beeldresolutie als \"DPI\" labelt, hoewel het technisch PPI is. Het afbeeldingsbestand slaat pixels op, geen punten. De punten bestaan alleen wanneer de afbeelding wordt afgedrukt. In de praktijk lost het begrijpen dat pixelafmetingen het belangrijkst zijn — voor zowel scherm als afdruk — de meeste verwarring op.",
      p6: "Gebruik onze DPI-calculator om afdrukafmetingen te bepalen, of de PPI-calculator om de pixeldichtheid van elk scherm te vinden.",
    },
  },
  ar: {
    faq: [
      { question: "هل يمكنني استخدام DPI و PPI بالتبادل؟", answer: "في الاستخدام العادي، يبدّل كثير من الناس بين المصطلحين. لكن DPI تقنياً ينطبق على الطابعات (نقاط الحبر في البوصة)، بينما PPI ينطبق على الشاشات والصور الرقمية (بكسلات في البوصة). استخدام المصطلح الصحيح يتجنب الغموض في البيئات المهنية." },
      { question: "هل 300 DPI نفس 300 PPI؟", answer: "عند الإشارة إلى ملف صورة، '300 DPI' عادة تعني 300 PPI — الصورة تحتوي على 300 بكسل في البوصة عند حجم الطباعة المقصود. DPI الفعلي للطابعة (غالباً 720-2880) يحدد مدى دقة إعادة إنتاج تلك البكسلات بنقاط الحبر." },
      { question: "أيهما أهم لتصميم الويب، DPI أم PPI؟", answer: "لا هذا ولا ذاك. متصفحات الويب تتجاهل بيانات DPI/PPI في ملفات الصور. فقط أبعاد البكسل هي المهمة لعرض الويب. صورة 1200x800 تُعرض بنفس الطريقة على الشاشة بغض النظر عن إعداد DPI." },
      { question: "لماذا تستخدم محررات الصور 72 أو 96 DPI كافتراضي؟", answer: "72 DPI كانت دقة شاشة Mac القديمة، و96 DPI هي الافتراضية لـ Windows. هذه القيم الافتراضية لا تؤثر على كيفية ظهور الصورة على الشاشة — فقط تؤثر على حساب حجم الطباعة الافتراضي." },
    ],
    body: {
      heading1: "إجابة سريعة",
      p1: "DPI (نقاط في البوصة) هو مقياس للطابعة. يقيس عدد نقاط الحبر الصغيرة التي تضعها الطابعة في كل بوصة. PPI (بكسلات في البوصة) هو مقياس للشاشة والصورة. يقيس عدد البكسلات المكتظة في كل بوصة من شاشة أو ملف رقمي. كلاهما يصف الكثافة لكل بوصة، لكنهما ينطبقان على سياقات مختلفة.",
      heading2: "مقارنة جنباً إلى جنب",
      th1: "السمة", th2: "DPI (نقاط في البوصة)", th3: "PPI (بكسلات في البوصة)",
      td1_1: "يعني", td1_2: "نقاط في البوصة", td1_3: "بكسلات في البوصة",
      td2_1: "ينطبق على", td2_2: "الطابعات والطباعة", td2_3: "الشاشات والصور الرقمية",
      td3_1: "يقيس", td3_2: "كثافة نقاط الحبر", td3_3: "كثافة البكسل",
      td4_1: "القيم النموذجية", td4_2: "600–2880 (طابعات)", td4_3: "72–460 (شاشات)",
      td5_1: "القيمة الأعلى تعني", td5_2: "مطبوعات أكثر سلاسة ودقة", td5_3: "شاشة أكثر حدة ووضوحاً",
      td6_1: "يتحكم به", td6_2: "جهاز/برنامج تشغيل الطابعة", td6_3: "جهاز الشاشة",
      td7_1: "يؤثر على حجم الملف؟", td7_2: "لا (بيانات وصفية فقط)", td7_3: "لا (بيانات وصفية فقط)",
      heading3: "متى ينطبق DPI",
      p2: "DPI مهم عند الطباعة. إعداد DPI لطابعتك يحدد مدى دقة إعادة إنتاج بيانات الصورة. طابعة ليزر 1200 DPI يمكنها وضع نقاط الحبر بدقة أكبر بكثير من طابعة 300 DPI، مما ينتج تدرجات أكثر سلاسة ونصوصاً أدق.",
      p3: "عندما يقول شخص \"احفظ هذه الصورة عند 300 DPI\"، عادة يعني 300 PPI — يريد 300 بكسل في البوصة عند حجم الطباعة المقصود. DPI الفعلي للطابعة هو مواصفة جهاز منفصلة.",
      heading4: "متى ينطبق PPI",
      p4: "PPI مهم للشاشات وملفات الصور. شاشتك لها PPI ثابت يحدده دقتها وحجمها الفيزيائي. عند إعداد صور لحجم طباعة محدد، PPI يخبرك بعدد البكسلات المطلوبة. عند 300 PPI، طباعة 10x8 بوصات تتطلب صورة 3000x2400 بكسل.",
      heading5: "الخلط الشائع",
      p5: "الخلط ينشأ لأن برامج مثل Photoshop تسمّي دقة الصورة \"DPI\" رغم أنها تقنياً PPI. ملف الصورة يخزن بكسلات وليس نقاطاً. النقاط توجد فقط عند طباعة الصورة. عملياً، فهم أن أبعاد البكسل هي المهمة — لكل من الشاشة والطباعة — يحل معظم الخلط.",
      p6: "استخدم حاسبة DPI لتحديد أبعاد الطباعة، أو حاسبة PPI لمعرفة كثافة البكسل لأي شاشة.",
    },
  },
  tr: {
    faq: [
      { question: "DPI ve PPI'yi birbirinin yerine kullanabilir miyim?", answer: "Günlük kullanımda birçok kişi terimleri birbirine karıştırır. Ancak DPI teknik olarak yazıcılara (inç başına mürekkep noktası), PPI ise ekranlara ve dijital görüntülere (inç başına piksel) uygulanır. Doğru terimi kullanmak profesyonel ortamlarda belirsizliği önler." },
      { question: "300 DPI, 300 PPI ile aynı mıdır?", answer: "Bir görüntü dosyasından bahsederken '300 DPI' genellikle 300 PPI anlamına gelir — görüntü, hedeflenen baskı boyutunda inç başına 300 piksele sahiptir. Yazıcının gerçek DPI'si (genellikle 720-2880) bu piksellerin mürekkep noktalarıyla ne kadar hassas yeniden üretileceğini belirler." },
      { question: "Web tasarımı için DPI mi yoksa PPI mi daha önemli?", answer: "Hiçbiri. Web tarayıcıları görüntü dosyalarındaki DPI/PPI meta verilerini yok sayar. Web gösterimi için yalnızca piksel boyutları önemlidir. 1200x800'lük bir görüntü, DPI ayarından bağımsız olarak ekranda aynı şekilde render edilir." },
      { question: "Görüntü editörleri neden varsayılan olarak 72 veya 96 DPI kullanır?", answer: "72 DPI, Mac'in eski ekran çözünürlüğüydü ve 96 DPI, Windows varsayılanıdır. Bu varsayılanlar görüntünün ekranda nasıl göründüğünü etkilemez — yalnızca varsayılan baskı boyutu hesaplamasını etkiler." },
    ],
    body: {
      heading1: "Hızlı Cevap",
      p1: "DPI (inç başına nokta) bir yazıcı metriğidir. Bir yazıcının inç başına kaç küçük mürekkep noktası bıraktığını ölçer. PPI (inç başına piksel) bir ekran ve görüntü metriğidir. Bir ekranın veya dijital dosyanın her inçinde kaç piksel olduğunu ölçer. Her ikisi de inç başına yoğunluğu tanımlar, ancak farklı bağlamlara uygulanır.",
      heading2: "Yan Yana Karşılaştırma",
      th1: "Özellik", th2: "DPI (İnç Başına Nokta)", th3: "PPI (İnç Başına Piksel)",
      td1_1: "Anlamı", td1_2: "İnç başına nokta", td1_3: "İnç başına piksel",
      td2_1: "Uygulandığı alan", td2_2: "Yazıcılar ve baskı", td2_3: "Ekranlar ve dijital görüntüler",
      td3_1: "Ölçtüğü", td3_2: "Mürekkep noktası yoğunluğu", td3_3: "Piksel yoğunluğu",
      td4_1: "Tipik değerler", td4_2: "600–2880 (yazıcılar)", td4_3: "72–460 (ekranlar)",
      td5_1: "Yüksek değer", td5_2: "Daha pürüzsüz, ince baskılar", td5_3: "Daha keskin, net ekran",
      td6_1: "Kontrol eden", td6_2: "Yazıcı donanımı/sürücüsü", td6_3: "Ekran donanımı",
      td7_1: "Dosya boyutunu etkiler mi?", td7_2: "Hayır (yalnızca meta veri)", td7_3: "Hayır (yalnızca meta veri)",
      heading3: "DPI Ne Zaman Geçerlidir",
      p2: "DPI yazdırırken geçerlidir. Yazıcınızın DPI ayarı, görüntü verilerini ne kadar hassas yeniden üretebileceğini belirler. 1200 DPI'lik bir lazer yazıcı, 300 DPI'lik bir yazıcıdan çok daha hassas mürekkep noktaları bırakabilir ve daha pürüzsüz degradeler ile daha ince metin üretir.",
      p3: "Birisi \"bu görüntüyü 300 DPI'de kaydet\" dediğinde, genellikle 300 PPI'yi kasteder — hedeflenen baskı boyutunda inç başına 300 piksel ister. Yazıcının gerçek DPI'si ayrı bir donanım özelliğidir.",
      heading4: "PPI Ne Zaman Geçerlidir",
      p4: "PPI ekranlar ve görüntü dosyaları için geçerlidir. Monitörünüzün çözünürlüğü ve fiziksel boyutu tarafından belirlenen sabit bir PPI'si vardır. Belirli bir baskı boyutu için görüntü hazırlarken, PPI kaç piksele ihtiyacınız olduğunu söyler. 300 PPI'de, 10x8 inçlik bir baskı 3000x2400 piksellik bir görüntü gerektirir.",
      heading5: "Yaygın Karışıklık",
      p5: "Karışıklık, Photoshop gibi yazılımların görüntü çözünürlüğünü teknik olarak PPI olmasına rağmen \"DPI\" olarak etiketlemesinden kaynaklanır. Görüntü dosyası piksel depolar, nokta değil. Noktalar yalnızca görüntü yazdırıldığında var olur. Pratikte, piksel boyutlarının önemli olduğunu anlamak — hem ekran hem baskı için — çoğu karışıklığı çözer.",
      p6: "Baskı boyutlarını belirlemek için DPI Hesaplayıcımızı veya herhangi bir ekranın piksel yoğunluğunu bulmak için PPI Hesaplayıcımızı kullanın.",
    },
  },
  pl: {
    faq: [
      { question: "Czy mogę używać DPI i PPI zamiennie?", answer: "W codziennym użyciu wiele osób myli te terminy. Jednak DPI technicznie odnosi się do drukarek (punkty atramentu na cal), a PPI do ekranów i obrazów cyfrowych (piksele na cal). Używanie prawidłowego terminu zapobiega niejednoznaczności w środowiskach profesjonalnych." },
      { question: "Czy 300 DPI to samo co 300 PPI?", answer: "Przy odwoływaniu się do pliku graficznego, '300 DPI' zwykle oznacza 300 PPI — obraz ma 300 pikseli na cal w zamierzonym rozmiarze wydruku. Rzeczywiste DPI drukarki (często 720-2880) określa, jak dokładnie te piksele są odtwarzane kropkami atramentu." },
      { question: "Co jest ważniejsze dla projektowania stron, DPI czy PPI?", answer: "Żadne z nich. Przeglądarki internetowe ignorują metadane DPI/PPI w plikach graficznych. Tylko wymiary pikselowe mają znaczenie dla wyświetlania w sieci. Obraz 1200x800 renderuje się tak samo na ekranie niezależnie od ustawienia DPI." },
      { question: "Dlaczego edytory graficzne domyślnie używają 72 lub 96 DPI?", answer: "72 DPI to historyczna rozdzielczość ekranu Maca, a 96 DPI to domyślna wartość Windows. Te wartości domyślne nie wpływają na sposób wyświetlania obrazu na ekranie — wpływają tylko na domyślne obliczenie rozmiaru wydruku." },
    ],
    body: {
      heading1: "Szybka odpowiedź",
      p1: "DPI (punkty na cal) to metryka drukarki. Mierzy, ile maleńkich kropek atramentu drukarka nakłada na cal. PPI (piksele na cal) to metryka ekranu i obrazu. Mierzy, ile pikseli jest upakowanych w każdym calu wyświetlacza lub pliku cyfrowego. Oba opisują gęstość na cal, ale dotyczą różnych kontekstów.",
      heading2: "Porównanie obok siebie",
      th1: "Cecha", th2: "DPI (Punkty na cal)", th3: "PPI (Piksele na cal)",
      td1_1: "Oznacza", td1_2: "Punkty na cal", td1_3: "Piksele na cal",
      td2_1: "Dotyczy", td2_2: "Drukarek i druku", td2_3: "Ekranów i obrazów cyfrowych",
      td3_1: "Mierzy", td3_2: "Gęstość kropek atramentu", td3_3: "Gęstość pikseli",
      td4_1: "Typowe wartości", td4_2: "600–2880 (drukarki)", td4_3: "72–460 (ekrany)",
      td5_1: "Wyższa wartość oznacza", td5_2: "Gładsze, drobniejsze wydruki", td5_3: "Ostrzejszy, wyraźniejszy obraz",
      td6_1: "Kontrolowane przez", td6_2: "Sprzęt/sterownik drukarki", td6_3: "Sprzęt wyświetlacza",
      td7_1: "Wpływa na rozmiar pliku?", td7_2: "Nie (tylko metadane)", td7_3: "Nie (tylko metadane)",
      heading3: "Kiedy DPI ma zastosowanie",
      p2: "DPI jest istotne przy drukowaniu. Ustawienie DPI drukarki określa, jak dokładnie może odtworzyć dane obrazu. Drukarka laserowa 1200 DPI może nakładać kropki atramentu znacznie precyzyjniej niż drukarka 300 DPI, produkując gładsze gradienty i drobniejszy tekst.",
      p3: "Gdy ktoś mówi \"zapisz ten obraz w 300 DPI\", zwykle ma na myśli 300 PPI — chce 300 pikseli na cal w zamierzonym rozmiarze wydruku. Rzeczywiste DPI drukarki to oddzielna specyfikacja sprzętowa.",
      heading4: "Kiedy PPI ma zastosowanie",
      p4: "PPI jest istotne dla ekranów i plików graficznych. Monitor ma stałe PPI określone przez jego rozdzielczość i fizyczny rozmiar. Przy przygotowywaniu obrazów do określonego rozmiaru wydruku, PPI mówi, ile pikseli potrzebujesz. Przy 300 PPI wydruk 10x8 cali wymaga obrazu 3000x2400 pikseli.",
      heading5: "Częste nieporozumienie",
      p5: "Nieporozumienie wynika z tego, że oprogramowanie takie jak Photoshop oznacza rozdzielczość obrazu jako \"DPI\", choć technicznie to PPI. Plik graficzny przechowuje piksele, nie kropki. Kropki istnieją tylko gdy obraz jest drukowany. W praktyce zrozumienie, że wymiary pikselowe są najważniejsze — zarówno dla ekranu jak i druku — rozwiązuje większość nieporozumień.",
      p6: "Użyj naszego Kalkulatora DPI do określenia wymiarów wydruku lub Kalkulatora PPI do znalezienia gęstości pikseli dowolnego ekranu.",
    },
  },
  id: {
    faq: [
      { question: "Bisakah saya menggunakan DPI dan PPI secara bergantian?", answer: "Dalam penggunaan kasual, banyak orang menukar istilah tersebut. Namun, DPI secara teknis berlaku untuk printer (titik tinta per inci), sementara PPI berlaku untuk layar dan gambar digital (piksel per inci). Menggunakan istilah yang benar menghindari ambiguitas di lingkungan profesional." },
      { question: "Apakah 300 DPI sama dengan 300 PPI?", answer: "Saat merujuk ke file gambar, '300 DPI' biasanya berarti 300 PPI — gambar memiliki 300 piksel per inci pada ukuran cetak yang dimaksud. DPI aktual printer (sering 720-2880) menentukan seberapa halus piksel tersebut direproduksi dengan titik tinta." },
      { question: "Mana yang lebih penting untuk desain web, DPI atau PPI?", answer: "Tidak keduanya. Browser web mengabaikan metadata DPI/PPI dalam file gambar. Hanya dimensi piksel yang penting untuk tampilan web. Gambar 1200x800 dirender sama di layar terlepas dari pengaturan DPI-nya." },
      { question: "Mengapa editor gambar default ke 72 atau 96 DPI?", answer: "72 DPI adalah resolusi layar lama Mac, dan 96 DPI adalah default Windows. Default ini tidak mempengaruhi tampilan gambar di layar — hanya mempengaruhi perhitungan ukuran cetak default." },
    ],
    body: {
      heading1: "Jawaban Cepat",
      p1: "DPI (titik per inci) adalah metrik printer. Mengukur berapa banyak titik tinta kecil yang ditempatkan printer per inci. PPI (piksel per inci) adalah metrik layar dan gambar. Mengukur berapa banyak piksel yang dikemas dalam setiap inci layar atau file digital. Keduanya menggambarkan kepadatan per inci, tetapi berlaku untuk konteks yang berbeda.",
      heading2: "Perbandingan Berdampingan",
      th1: "Atribut", th2: "DPI (Titik Per Inci)", th3: "PPI (Piksel Per Inci)",
      td1_1: "Singkatan dari", td1_2: "Titik per inci", td1_3: "Piksel per inci",
      td2_1: "Berlaku untuk", td2_2: "Printer dan pencetakan", td2_3: "Layar dan gambar digital",
      td3_1: "Mengukur", td3_2: "Kepadatan titik tinta", td3_3: "Kepadatan piksel",
      td4_1: "Nilai tipikal", td4_2: "600–2880 (printer)", td4_3: "72–460 (layar)",
      td5_1: "Nilai lebih tinggi berarti", td5_2: "Cetakan lebih halus dan rapi", td5_3: "Tampilan lebih tajam dan jernih",
      td6_1: "Dikontrol oleh", td6_2: "Hardware/driver printer", td6_3: "Hardware layar",
      td7_1: "Mempengaruhi ukuran file?", td7_2: "Tidak (metadata saja)", td7_3: "Tidak (metadata saja)",
      heading3: "Kapan DPI Berlaku",
      p2: "DPI relevan saat Anda mencetak. Pengaturan DPI printer menentukan seberapa halus ia dapat mereproduksi data gambar. Printer laser 1200 DPI dapat menempatkan titik tinta jauh lebih presisi daripada printer 300 DPI, menghasilkan gradien lebih halus dan teks lebih rapi.",
      p3: "Saat seseorang mengatakan \"simpan gambar ini di 300 DPI\", mereka biasanya bermaksud 300 PPI — mereka menginginkan 300 piksel per inci pada ukuran cetak yang dimaksud. DPI aktual printer adalah spesifikasi hardware terpisah.",
      heading4: "Kapan PPI Berlaku",
      p4: "PPI relevan untuk layar dan file gambar. Monitor Anda memiliki PPI tetap yang ditentukan oleh resolusi dan ukuran fisiknya. Saat menyiapkan gambar untuk ukuran cetak tertentu, PPI memberi tahu berapa banyak piksel yang dibutuhkan. Pada 300 PPI, cetakan 10x8 inci membutuhkan gambar 3000x2400 piksel.",
      heading5: "Kebingungan Umum",
      p5: "Kebingungan muncul karena software seperti Photoshop melabeli resolusi gambar sebagai \"DPI\" padahal secara teknis itu PPI. File gambar menyimpan piksel, bukan titik. Titik hanya ada saat gambar dicetak. Secara praktis, memahami bahwa dimensi piksel adalah yang penting — baik untuk layar maupun cetak — menyelesaikan sebagian besar kebingungan.",
      p6: "Gunakan Kalkulator DPI kami untuk menentukan dimensi cetak, atau Kalkulator PPI untuk menemukan kepadatan piksel layar apa pun.",
    },
  },
  ru: {
    faq: [
      { question: "Можно ли использовать DPI и PPI взаимозаменяемо?", answer: "В обычном использовании многие люди путают эти термины. Однако DPI технически относится к принтерам (точки чернил на дюйм), а PPI — к экранам и цифровым изображениям (пиксели на дюйм). Использование правильного термина устраняет неоднозначность в профессиональной среде." },
      { question: "300 DPI — это то же самое, что 300 PPI?", answer: "При упоминании файла изображения '300 DPI' обычно означает 300 PPI — изображение имеет 300 пикселей на дюйм при предполагаемом размере печати. Фактический DPI принтера (часто 720-2880) определяет, насколько точно эти пиксели воспроизводятся чернильными точками." },
      { question: "Что важнее для веб-дизайна — DPI или PPI?", answer: "Ни то, ни другое. Веб-браузеры игнорируют метаданные DPI/PPI в файлах изображений. Для отображения в вебе имеют значение только размеры в пикселях. Изображение 1200x800 отображается на экране одинаково независимо от настройки DPI." },
      { question: "Почему графические редакторы по умолчанию используют 72 или 96 DPI?", answer: "72 DPI — это историческое разрешение экрана Mac, а 96 DPI — стандарт Windows. Эти значения не влияют на отображение изображения на экране — они влияют только на расчёт размера печати по умолчанию." },
    ],
    body: {
      heading1: "Быстрый ответ",
      p1: "DPI (точек на дюйм) — это метрика принтера. Она измеряет, сколько крошечных чернильных точек принтер наносит на дюйм. PPI (пикселей на дюйм) — это метрика экрана и изображения. Она измеряет, сколько пикселей упаковано в каждом дюйме дисплея или цифрового файла. Оба описывают плотность на дюйм, но применяются к разным контекстам.",
      heading2: "Сравнение",
      th1: "Атрибут", th2: "DPI (Точек на дюйм)", th3: "PPI (Пикселей на дюйм)",
      td1_1: "Расшифровка", td1_2: "Точек на дюйм", td1_3: "Пикселей на дюйм",
      td2_1: "Применяется к", td2_2: "Принтерам и печати", td2_3: "Экранам и цифровым изображениям",
      td3_1: "Измеряет", td3_2: "Плотность чернильных точек", td3_3: "Плотность пикселей",
      td4_1: "Типичные значения", td4_2: "600–2880 (принтеры)", td4_3: "72–460 (экраны)",
      td5_1: "Большее значение означает", td5_2: "Более гладкие, чёткие отпечатки", td5_3: "Более чёткое, ясное изображение",
      td6_1: "Контролируется", td6_2: "Оборудованием/драйвером принтера", td6_3: "Оборудованием дисплея",
      td7_1: "Влияет на размер файла?", td7_2: "Нет (только метаданные)", td7_3: "Нет (только метаданные)",
      heading3: "Когда применяется DPI",
      p2: "DPI актуален при печати. Настройка DPI принтера определяет, насколько точно он может воспроизвести данные изображения. Лазерный принтер 1200 DPI может наносить чернильные точки значительно точнее, чем принтер 300 DPI, создавая более плавные градиенты и тонкий текст.",
      p3: "Когда кто-то говорит «сохрани это изображение в 300 DPI», обычно имеется в виду 300 PPI — нужно 300 пикселей на дюйм при предполагаемом размере печати. Фактический DPI принтера — это отдельная аппаратная характеристика.",
      heading4: "Когда применяется PPI",
      p4: "PPI актуален для экранов и файлов изображений. Ваш монитор имеет фиксированный PPI, определяемый разрешением и физическим размером. При подготовке изображений для определённого размера печати PPI подскажет, сколько пикселей нужно. При 300 PPI для печати 10x8 дюймов требуется изображение 3000x2400 пикселей.",
      heading5: "Распространённая путаница",
      p5: "Путаница возникает из-за того, что программы вроде Photoshop обозначают разрешение изображения как «DPI», хотя технически это PPI. Файл изображения хранит пиксели, а не точки. Точки появляются только при печати изображения. На практике, понимание того, что размеры в пикселях — это главное, как для экрана, так и для печати, устраняет большую часть путаницы.",
      p6: "Используйте наш Калькулятор DPI для определения размеров печати или Калькулятор PPI для определения плотности пикселей любого экрана.",
    },
  },
};
