import type { PageContentMap } from "./types";

export const content: PageContentMap = {
  en: {
    faq: [],
    body: {
      lastUpdated: "Last updated: March 18, 2026",
      heading1: "Acceptance of Terms",
      p1: "By accessing or using FeetToPixels (feettopixels.com), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, do not use the Site.",
      heading2: "Description of Service",
      p2: "FeetToPixels provides free online unit conversion tools, calculators, and educational content related to pixels, DPI, PPI, and other measurement units (\"Services\"). These tools run entirely in your browser and are provided for informational and convenience purposes.",
      heading3: "Use of the Services",
      p3: "You agree to use the Services only for lawful purposes and in accordance with these Terms. You agree not to:",
      li1: "Use the Site in any way that violates applicable laws or regulations",
      li2: "Attempt to interfere with the proper functioning of the Site",
      li3: "Use automated scripts, bots, or scrapers to access the Site excessively",
      li4: "Attempt to gain unauthorized access to any part of the Site",
      li5: "Reproduce, distribute, or create derivative works from our content without permission",
      heading4: "Accuracy of Information",
      p4: "We strive to provide accurate conversion results and educational content. Our tools use mathematically exact conversion factors based on established standards (ISO, ANSI). However, we make no warranties regarding the accuracy, completeness, or suitability of the information provided. Results should be verified for mission-critical applications.",
      heading5: "Intellectual Property",
      p5: "All content on the Site, including text, graphics, logos, code, and tool designs, is the property of FeetToPixels and is protected by copyright and other intellectual property laws. You may use conversion results freely but may not reproduce our content, tools, or design without written permission.",
      heading6: "Disclaimer of Warranties",
      p6: "The Site and Services are provided \"as is\" and \"as available\" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Site will be uninterrupted, error-free, or free of viruses or other harmful components.",
      heading7: "Limitation of Liability",
      p7: "In no event shall FeetToPixels, its operators, or contributors be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Site or Services.",
      heading8: "Third-Party Content and Links",
      p8: "The Site may contain links to third-party websites or display third-party advertisements. We do not control or endorse third-party content and are not responsible for any third-party websites, products, or services.",
      heading9: "Advertising",
      p9: "The Site displays advertisements through third-party advertising networks, including Google AdSense. These advertisements help support the free Services we provide. Ad content is controlled by the advertising networks, not by FeetToPixels.",
      heading10: "Privacy",
      p10: "Your use of the Site is also governed by our Privacy Policy, which is incorporated into these Terms by reference.",
      heading11: "Modifications to Terms",
      p11: "We reserve the right to modify these Terms at any time. Changes take effect immediately upon posting. Your continued use of the Site after changes constitutes acceptance of the modified Terms.",
      heading12: "Termination",
      p12: "We reserve the right to terminate or restrict your access to the Site at our sole discretion, without notice, for any reason, including violation of these Terms.",
      heading13: "Governing Law",
      p13: "These Terms are governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or your use of the Site shall be resolved in the appropriate courts.",
      heading14: "Contact",
      p14: "If you have questions about these Terms, please contact us through our contact page.",
    },
  },
  es: {
    faq: [],
    body: {
      lastUpdated: "Última actualización: 18 de marzo de 2026",
      heading1: "Aceptación de los términos",
      p1: "Al acceder o usar FeetToPixels (feettopixels.com), aceptas estar vinculado por estos Términos de Servicio (\"Términos\"). Si no estás de acuerdo con estos Términos, no uses el Sitio.",
      heading2: "Descripción del servicio",
      p2: "FeetToPixels proporciona herramientas gratuitas de conversión de unidades en línea, calculadoras y contenido educativo relacionado con píxeles, DPI, PPI y otras unidades de medida (\"Servicios\"). Estas herramientas funcionan completamente en tu navegador y se proporcionan con fines informativos y de conveniencia.",
      heading3: "Uso de los servicios",
      p3: "Aceptas usar los Servicios solo con fines lícitos y de acuerdo con estos Términos. Aceptas no:",
      li1: "Usar el Sitio de cualquier manera que viole las leyes o regulaciones aplicables",
      li2: "Intentar interferir con el funcionamiento correcto del Sitio",
      li3: "Usar scripts automatizados, bots o scrapers para acceder al Sitio de manera excesiva",
      li4: "Intentar obtener acceso no autorizado a cualquier parte del Sitio",
      li5: "Reproducir, distribuir o crear obras derivadas de nuestro contenido sin permiso",
      heading4: "Precisión de la información",
      p4: "Nos esforzamos por proporcionar resultados de conversión precisos y contenido educativo. Nuestras herramientas utilizan factores de conversión matemáticamente exactos basados en estándares establecidos (ISO, ANSI). Sin embargo, no ofrecemos garantías respecto a la precisión, integridad o idoneidad de la información proporcionada.",
      heading5: "Propiedad intelectual",
      p5: "Todo el contenido del Sitio, incluyendo texto, gráficos, logotipos, código y diseños de herramientas, es propiedad de FeetToPixels y está protegido por derechos de autor y otras leyes de propiedad intelectual.",
      heading6: "Descargo de garantías",
      p6: "El Sitio y los Servicios se proporcionan \"tal cual\" y \"según disponibilidad\" sin garantías de ningún tipo, ya sean expresas o implícitas.",
      heading7: "Limitación de responsabilidad",
      p7: "En ningún caso FeetToPixels, sus operadores o colaboradores serán responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos derivados de tu uso del Sitio o los Servicios.",
      heading8: "Contenido y enlaces de terceros",
      p8: "El Sitio puede contener enlaces a sitios web de terceros o mostrar anuncios de terceros. No controlamos ni respaldamos el contenido de terceros.",
      heading9: "Publicidad",
      p9: "El Sitio muestra anuncios a través de redes publicitarias de terceros, incluyendo Google AdSense. Estos anuncios ayudan a respaldar los Servicios gratuitos que proporcionamos.",
      heading10: "Privacidad",
      p10: "Tu uso del Sitio también se rige por nuestra Política de Privacidad, que se incorpora a estos Términos por referencia.",
      heading11: "Modificaciones de los términos",
      p11: "Nos reservamos el derecho de modificar estos Términos en cualquier momento. Los cambios entran en vigor inmediatamente después de su publicación.",
      heading12: "Terminación",
      p12: "Nos reservamos el derecho de terminar o restringir tu acceso al Sitio a nuestra entera discreción, sin previo aviso, por cualquier motivo.",
      heading13: "Ley aplicable",
      p13: "Estos Términos se rigen por las leyes de los Estados Unidos. Cualquier disputa se resolverá en los tribunales apropiados.",
      heading14: "Contacto",
      p14: "Si tienes preguntas sobre estos Términos, contáctanos a través de nuestra página de contacto.",
    },
  },
  fr: {
    faq: [],
    body: {
      lastUpdated: "Dernière mise à jour : 18 mars 2026",
      heading1: "Acceptation des conditions",
      p1: "En accédant ou en utilisant FeetToPixels (feettopixels.com), vous acceptez d'être lié par ces Conditions d'Utilisation (\"Conditions\"). Si vous n'acceptez pas ces Conditions, n'utilisez pas le Site.",
      heading2: "Description du service",
      p2: "FeetToPixels fournit des outils gratuits de conversion d'unités en ligne, des calculateurs et du contenu éducatif relatif aux pixels, DPI, PPI et autres unités de mesure (\"Services\"). Ces outils fonctionnent entièrement dans votre navigateur.",
      heading3: "Utilisation des services",
      p3: "Vous acceptez d'utiliser les Services uniquement à des fins légales et conformément à ces Conditions. Vous acceptez de ne pas :",
      li1: "Utiliser le Site d'une manière qui enfreint les lois ou réglementations applicables",
      li2: "Tenter d'interférer avec le bon fonctionnement du Site",
      li3: "Utiliser des scripts automatisés, des bots ou des scrapers pour accéder au Site de manière excessive",
      li4: "Tenter d'obtenir un accès non autorisé à toute partie du Site",
      li5: "Reproduire, distribuer ou créer des œuvres dérivées de notre contenu sans autorisation",
      heading4: "Exactitude des informations",
      p4: "Nous nous efforçons de fournir des résultats de conversion précis et du contenu éducatif. Nos outils utilisent des facteurs de conversion mathématiquement exacts basés sur des normes établies (ISO, ANSI). Cependant, nous ne garantissons pas l'exactitude, l'exhaustivité ou l'adéquation des informations fournies.",
      heading5: "Propriété intellectuelle",
      p5: "Tout le contenu du Site, y compris le texte, les graphiques, les logos, le code et les designs d'outils, est la propriété de FeetToPixels et est protégé par le droit d'auteur.",
      heading6: "Exclusion de garanties",
      p6: "Le Site et les Services sont fournis \"tels quels\" et \"selon disponibilité\" sans garantie d'aucune sorte, expresse ou implicite.",
      heading7: "Limitation de responsabilité",
      p7: "En aucun cas FeetToPixels, ses opérateurs ou contributeurs ne seront responsables de dommages indirects, accessoires, spéciaux, consécutifs ou punitifs.",
      heading8: "Contenu et liens tiers",
      p8: "Le Site peut contenir des liens vers des sites web tiers ou afficher des publicités tierces. Nous ne contrôlons pas le contenu tiers.",
      heading9: "Publicité",
      p9: "Le Site affiche des publicités via des réseaux publicitaires tiers, dont Google AdSense. Ces publicités aident à soutenir les Services gratuits que nous fournissons.",
      heading10: "Confidentialité",
      p10: "Votre utilisation du Site est également régie par notre Politique de Confidentialité, incorporée dans ces Conditions par référence.",
      heading11: "Modifications des conditions",
      p11: "Nous nous réservons le droit de modifier ces Conditions à tout moment. Les changements prennent effet immédiatement après leur publication.",
      heading12: "Résiliation",
      p12: "Nous nous réservons le droit de résilier ou de restreindre votre accès au Site à notre seule discrétion, sans préavis.",
      heading13: "Droit applicable",
      p13: "Ces Conditions sont régies par les lois des États-Unis. Tout litige sera résolu devant les tribunaux compétents.",
      heading14: "Contact",
      p14: "Si vous avez des questions sur ces Conditions, veuillez nous contacter via notre page de contact.",
    },
  },
  de: {
    faq: [],
    body: {
      lastUpdated: "Zuletzt aktualisiert: 18. März 2026",
      heading1: "Annahme der Bedingungen",
      p1: "Durch den Zugriff auf oder die Nutzung von FeetToPixels (feettopixels.com) erklären Sie sich mit diesen Nutzungsbedingungen (\"Bedingungen\") einverstanden. Wenn Sie diesen Bedingungen nicht zustimmen, nutzen Sie die Website nicht.",
      heading2: "Beschreibung des Dienstes",
      p2: "FeetToPixels bietet kostenlose Online-Umrechnungstools, Rechner und Bildungsinhalte zu Pixeln, DPI, PPI und anderen Maßeinheiten (\"Dienste\"). Diese Tools laufen vollständig in Ihrem Browser.",
      heading3: "Nutzung der Dienste",
      p3: "Sie erklären sich damit einverstanden, die Dienste nur für rechtmäßige Zwecke und gemäß diesen Bedingungen zu nutzen. Sie verpflichten sich, nicht:",
      li1: "Die Website auf eine Weise zu nutzen, die gegen geltende Gesetze verstößt",
      li2: "Das ordnungsgemäße Funktionieren der Website zu stören",
      li3: "Automatisierte Skripte, Bots oder Scraper für übermäßigen Zugriff zu verwenden",
      li4: "Unbefugten Zugang zu Teilen der Website zu erlangen",
      li5: "Unsere Inhalte ohne Genehmigung zu reproduzieren, verbreiten oder abgeleitete Werke zu erstellen",
      heading4: "Genauigkeit der Informationen",
      p4: "Wir bemühen uns um genaue Konvertierungsergebnisse und Bildungsinhalte. Unsere Tools verwenden mathematisch exakte Umrechnungsfaktoren basierend auf etablierten Standards (ISO, ANSI). Wir übernehmen jedoch keine Gewährleistung für Genauigkeit, Vollständigkeit oder Eignung.",
      heading5: "Geistiges Eigentum",
      p5: "Alle Inhalte der Website, einschließlich Texte, Grafiken, Logos, Code und Tool-Designs, sind Eigentum von FeetToPixels und urheberrechtlich geschützt.",
      heading6: "Gewährleistungsausschluss",
      p6: "Die Website und Dienste werden \"wie besehen\" und \"wie verfügbar\" ohne jegliche Gewährleistung bereitgestellt.",
      heading7: "Haftungsbeschränkung",
      p7: "FeetToPixels, seine Betreiber oder Mitwirkenden haften in keinem Fall für indirekte, zufällige, besondere, Folge- oder Strafschäden.",
      heading8: "Inhalte und Links Dritter",
      p8: "Die Website kann Links zu Drittanbieter-Websites enthalten oder Werbung Dritter anzeigen. Wir kontrollieren keine Inhalte Dritter.",
      heading9: "Werbung",
      p9: "Die Website zeigt Werbung über Drittanbieter-Werbenetzwerke, einschließlich Google AdSense. Diese Werbung unterstützt die kostenlosen Dienste.",
      heading10: "Datenschutz",
      p10: "Ihre Nutzung der Website unterliegt auch unserer Datenschutzrichtlinie, die durch Bezugnahme in diese Bedingungen aufgenommen wird.",
      heading11: "Änderungen der Bedingungen",
      p11: "Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu ändern. Änderungen treten sofort nach Veröffentlichung in Kraft.",
      heading12: "Kündigung",
      p12: "Wir behalten uns das Recht vor, Ihren Zugang zur Website nach eigenem Ermessen und ohne Vorankündigung einzuschränken oder zu beenden.",
      heading13: "Anwendbares Recht",
      p13: "Diese Bedingungen unterliegen den Gesetzen der Vereinigten Staaten. Streitigkeiten werden vor den zuständigen Gerichten gelöst.",
      heading14: "Kontakt",
      p14: "Bei Fragen zu diesen Bedingungen kontaktieren Sie uns bitte über unsere Kontaktseite.",
    },
  },
  pt: {
    faq: [],
    body: {
      lastUpdated: "Última atualização: 18 de março de 2026",
      heading1: "Aceitação dos termos",
      p1: "Ao acessar ou usar o FeetToPixels (feettopixels.com), você concorda em ficar vinculado a estes Termos de Serviço (\"Termos\"). Se não concordar com estes Termos, não use o Site.",
      heading2: "Descrição do serviço",
      p2: "O FeetToPixels fornece ferramentas gratuitas de conversão de unidades online, calculadoras e conteúdo educativo relacionado a pixels, DPI, PPI e outras unidades de medida (\"Serviços\"). Essas ferramentas funcionam inteiramente no seu navegador.",
      heading3: "Uso dos serviços",
      p3: "Você concorda em usar os Serviços apenas para fins lícitos e de acordo com estes Termos. Você concorda em não:",
      li1: "Usar o Site de qualquer forma que viole leis ou regulamentos aplicáveis",
      li2: "Tentar interferir no funcionamento adequado do Site",
      li3: "Usar scripts automatizados, bots ou scrapers para acessar o Site excessivamente",
      li4: "Tentar obter acesso não autorizado a qualquer parte do Site",
      li5: "Reproduzir, distribuir ou criar obras derivadas do nosso conteúdo sem permissão",
      heading4: "Precisão das informações",
      p4: "Nos esforçamos para fornecer resultados de conversão precisos e conteúdo educativo. Nossas ferramentas usam fatores de conversão matematicamente exatos baseados em padrões estabelecidos (ISO, ANSI). No entanto, não garantimos a precisão, integridade ou adequação das informações.",
      heading5: "Propriedade intelectual",
      p5: "Todo o conteúdo do Site, incluindo texto, gráficos, logotipos, código e designs de ferramentas, é propriedade do FeetToPixels e protegido por direitos autorais.",
      heading6: "Isenção de garantias",
      p6: "O Site e os Serviços são fornecidos \"como estão\" e \"conforme disponíveis\" sem garantias de qualquer tipo.",
      heading7: "Limitação de responsabilidade",
      p7: "Em nenhum caso o FeetToPixels, seus operadores ou colaboradores serão responsáveis por danos indiretos, incidentais, especiais, consequenciais ou punitivos.",
      heading8: "Conteúdo e links de terceiros",
      p8: "O Site pode conter links para sites de terceiros ou exibir anúncios de terceiros. Não controlamos conteúdo de terceiros.",
      heading9: "Publicidade",
      p9: "O Site exibe anúncios através de redes de publicidade de terceiros, incluindo Google AdSense. Esses anúncios ajudam a sustentar os Serviços gratuitos.",
      heading10: "Privacidade",
      p10: "O uso do Site também é regido pela nossa Política de Privacidade, incorporada a estes Termos por referência.",
      heading11: "Modificações dos termos",
      p11: "Reservamo-nos o direito de modificar estes Termos a qualquer momento. As alterações entram em vigor imediatamente após a publicação.",
      heading12: "Rescisão",
      p12: "Reservamo-nos o direito de encerrar ou restringir seu acesso ao Site a nosso exclusivo critério, sem aviso prévio.",
      heading13: "Lei aplicável",
      p13: "Estes Termos são regidos pelas leis dos Estados Unidos. Disputas serão resolvidas nos tribunais competentes.",
      heading14: "Contato",
      p14: "Se tiver dúvidas sobre estes Termos, entre em contato conosco através da nossa página de contato.",
    },
  },
  hi: {
    faq: [],
    body: {
      lastUpdated: "अंतिम अपडेट: 18 मार्च, 2026",
      heading1: "शर्तों की स्वीकृति",
      p1: "FeetToPixels (feettopixels.com) तक पहुंचकर या उसका उपयोग करके, आप इन सेवा की शर्तों (\"शर्तें\") से बाध्य होने के लिए सहमत हैं। यदि आप इन शर्तों से सहमत नहीं हैं, तो साइट का उपयोग न करें।",
      heading2: "सेवा का विवरण",
      p2: "FeetToPixels पिक्सेल, DPI, PPI और अन्य माप इकाइयों से संबंधित मुफ्त ऑनलाइन इकाई रूपांतरण उपकरण, कैलकुलेटर और शैक्षिक सामग्री प्रदान करता है (\"सेवाएं\")। ये उपकरण पूरी तरह से आपके ब्राउज़र में चलते हैं।",
      heading3: "सेवाओं का उपयोग",
      p3: "आप सेवाओं का उपयोग केवल वैध उद्देश्यों के लिए और इन शर्तों के अनुसार करने के लिए सहमत हैं। आप सहमत हैं कि:",
      li1: "साइट का उपयोग किसी भी तरह से न करें जो लागू कानूनों का उल्लंघन करती हो",
      li2: "साइट के उचित कार्य में हस्तक्षेप करने का प्रयास न करें",
      li3: "साइट तक अत्यधिक पहुंच के लिए स्वचालित स्क्रिप्ट, बॉट या स्क्रैपर का उपयोग न करें",
      li4: "साइट के किसी भी हिस्से तक अनधिकृत पहुंच प्राप्त करने का प्रयास न करें",
      li5: "बिना अनुमति के हमारी सामग्री की प्रतिकृति, वितरण या व्युत्पन्न कार्य न बनाएं",
      heading4: "सूचना की सटीकता",
      p4: "हम सटीक रूपांतरण परिणाम और शैक्षिक सामग्री प्रदान करने का प्रयास करते हैं। हमारे उपकरण स्थापित मानकों (ISO, ANSI) पर आधारित गणितीय रूप से सटीक रूपांतरण कारकों का उपयोग करते हैं।",
      heading5: "बौद्धिक संपदा",
      p5: "साइट पर सभी सामग्री FeetToPixels की संपत्ति है और कॉपीराइट द्वारा संरक्षित है।",
      heading6: "गारंटी का अस्वीकरण",
      p6: "साइट और सेवाएं बिना किसी वारंटी के \"जैसा है\" और \"जैसा उपलब्ध है\" प्रदान की जाती हैं।",
      heading7: "दायित्व की सीमा",
      p7: "किसी भी स्थिति में FeetToPixels, इसके ऑपरेटर या योगदानकर्ता किसी भी अप्रत्यक्ष, आकस्मिक, विशेष या दंडात्मक क्षति के लिए उत्तरदायी नहीं होंगे।",
      heading8: "तृतीय-पक्ष सामग्री और लिंक",
      p8: "साइट में तृतीय-पक्ष वेबसाइटों के लिंक या विज्ञापन हो सकते हैं। हम तृतीय-पक्ष सामग्री को नियंत्रित नहीं करते।",
      heading9: "विज्ञापन",
      p9: "साइट Google AdSense सहित तृतीय-पक्ष विज्ञापन नेटवर्क के माध्यम से विज्ञापन प्रदर्शित करती है।",
      heading10: "गोपनीयता",
      p10: "साइट का आपका उपयोग हमारी गोपनीयता नीति द्वारा भी शासित है।",
      heading11: "शर्तों में संशोधन",
      p11: "हम किसी भी समय इन शर्तों को संशोधित करने का अधिकार सुरक्षित रखते हैं।",
      heading12: "समाप्ति",
      p12: "हम बिना सूचना के, किसी भी कारण से साइट तक आपकी पहुंच को समाप्त या प्रतिबंधित करने का अधिकार सुरक्षित रखते हैं।",
      heading13: "शासी कानून",
      p13: "ये शर्तें संयुक्त राज्य अमेरिका के कानूनों द्वारा शासित हैं।",
      heading14: "संपर्क",
      p14: "यदि इन शर्तों के बारे में आपके कोई प्रश्न हैं, तो कृपया हमारे संपर्क पृष्ठ के माध्यम से हमसे संपर्क करें।",
    },
  },
  ja: {
    faq: [],
    body: {
      lastUpdated: "最終更新日: 2026年3月18日",
      heading1: "利用規約の同意",
      p1: "FeetToPixels（feettopixels.com）にアクセスまたは使用することにより、この利用規約（「規約」）に拘束されることに同意するものとします。これらの規約に同意しない場合は、サイトを使用しないでください。",
      heading2: "サービスの説明",
      p2: "FeetToPixelsは、ピクセル、DPI、PPI、その他の測定単位に関連する無料のオンライン単位変換ツール、計算機、教育コンテンツ（「サービス」）を提供します。これらのツールは完全にブラウザ内で動作します。",
      heading3: "サービスの利用",
      p3: "本規約に従い、合法的な目的でのみサービスを使用することに同意するものとします。以下の行為をしないことに同意します：",
      li1: "適用法令に違反する方法でサイトを使用すること",
      li2: "サイトの正常な機能を妨害しようとすること",
      li3: "自動スクリプト、ボット、スクレイパーによるサイトへの過度なアクセス",
      li4: "サイトの一部への不正アクセスの試み",
      li5: "許可なくコンテンツの複製、配布、派生物の作成",
      heading4: "情報の正確性",
      p4: "正確な変換結果と教育コンテンツの提供に努めています。ツールは確立された基準（ISO、ANSI）に基づく数学的に正確な変換係数を使用していますが、情報の正確性、完全性、適合性を保証するものではありません。",
      heading5: "知的財産権",
      p5: "サイト上のすべてのコンテンツはFeetToPixelsの所有物であり、著作権法で保護されています。",
      heading6: "保証の免責",
      p6: "サイトおよびサービスは、明示・黙示を問わず、いかなる種類の保証もなく「現状のまま」提供されます。",
      heading7: "責任の制限",
      p7: "いかなる場合も、FeetToPixels、その運営者または貢献者は、間接的、付随的、特別、結果的または懲罰的損害について責任を負いません。",
      heading8: "第三者コンテンツとリンク",
      p8: "サイトには第三者ウェブサイトへのリンクや広告が含まれる場合があります。第三者コンテンツを管理していません。",
      heading9: "広告",
      p9: "サイトはGoogle AdSenseを含む第三者広告ネットワークを通じて広告を表示します。",
      heading10: "プライバシー",
      p10: "サイトの使用は、本規約に組み込まれたプライバシーポリシーにも準拠します。",
      heading11: "規約の変更",
      p11: "本規約はいつでも変更する権利を留保します。変更は掲載と同時に有効になります。",
      heading12: "終了",
      p12: "理由の如何を問わず、予告なくサイトへのアクセスを終了または制限する権利を留保します。",
      heading13: "準拠法",
      p13: "本規約は米国の法律に準拠します。紛争は適切な裁判所で解決されます。",
      heading14: "お問い合わせ",
      p14: "本規約についてご質問がある場合は、お問い合わせページからご連絡ください。",
    },
  },
  ko: {
    faq: [],
    body: {
      lastUpdated: "최종 업데이트: 2026년 3월 18일",
      heading1: "약관 동의",
      p1: "FeetToPixels(feettopixels.com)에 접근하거나 사용함으로써 본 서비스 약관(\"약관\")에 구속되는 것에 동의합니다. 약관에 동의하지 않으면 사이트를 사용하지 마십시오.",
      heading2: "서비스 설명",
      p2: "FeetToPixels는 픽셀, DPI, PPI 및 기타 측정 단위와 관련된 무료 온라인 단위 변환 도구, 계산기 및 교육 콘텐츠(\"서비스\")를 제공합니다. 이 도구는 전적으로 브라우저에서 실행됩니다.",
      heading3: "서비스 이용",
      p3: "본 약관에 따라 합법적인 목적으로만 서비스를 사용하는 데 동의합니다. 다음 행위를 하지 않을 것에 동의합니다:",
      li1: "적용 법률을 위반하는 방식으로 사이트를 사용하는 행위",
      li2: "사이트의 정상적인 기능을 방해하려는 시도",
      li3: "자동 스크립트, 봇, 스크레이퍼를 이용한 과도한 접근",
      li4: "사이트 일부에 대한 무단 접근 시도",
      li5: "허가 없이 콘텐츠를 복제, 배포 또는 파생 작품 생성",
      heading4: "정보의 정확성",
      p4: "정확한 변환 결과와 교육 콘텐츠를 제공하기 위해 노력합니다. 도구는 확립된 표준(ISO, ANSI)에 기반한 수학적으로 정확한 변환 계수를 사용하지만, 정보의 정확성, 완전성 또는 적합성을 보증하지 않습니다.",
      heading5: "지적 재산권",
      p5: "사이트의 모든 콘텐츠는 FeetToPixels의 자산이며 저작권법으로 보호됩니다.",
      heading6: "보증 면책",
      p6: "사이트와 서비스는 명시적이든 묵시적이든 어떠한 종류의 보증도 없이 \"있는 그대로\" 제공됩니다.",
      heading7: "책임 제한",
      p7: "FeetToPixels, 운영자 또는 기여자는 어떠한 경우에도 간접적, 부수적, 특별, 결과적 또는 징벌적 손해에 대해 책임을 지지 않습니다.",
      heading8: "제3자 콘텐츠 및 링크",
      p8: "사이트에 제3자 웹사이트 링크나 광고가 포함될 수 있습니다. 제3자 콘텐츠를 통제하지 않습니다.",
      heading9: "광고",
      p9: "사이트는 Google AdSense를 포함한 제3자 광고 네트워크를 통해 광고를 표시합니다.",
      heading10: "개인정보 보호",
      p10: "사이트 사용은 본 약관에 참조로 통합된 개인정보 처리방침에도 적용됩니다.",
      heading11: "약관 수정",
      p11: "약관을 언제든지 수정할 권리를 보유합니다. 변경 사항은 게시 즉시 효력이 발생합니다.",
      heading12: "해지",
      p12: "사유를 불문하고 사전 통지 없이 사이트 접근을 종료하거나 제한할 권리를 보유합니다.",
      heading13: "준거법",
      p13: "본 약관은 미국 법률에 의해 규율됩니다. 분쟁은 적절한 법원에서 해결됩니다.",
      heading14: "문의",
      p14: "약관에 대한 질문이 있으시면 문의 페이지를 통해 연락해 주세요.",
    },
  },
  it: {
    faq: [],
    body: {
      lastUpdated: "Ultimo aggiornamento: 18 marzo 2026",
      heading1: "Accettazione dei termini",
      p1: "Accedendo o utilizzando FeetToPixels (feettopixels.com), accetti di essere vincolato da questi Termini di Servizio (\"Termini\"). Se non accetti questi Termini, non utilizzare il Sito.",
      heading2: "Descrizione del servizio",
      p2: "FeetToPixels fornisce strumenti gratuiti di conversione unità online, calcolatori e contenuti educativi relativi a pixel, DPI, PPI e altre unità di misura (\"Servizi\").",
      heading3: "Uso dei servizi",
      p3: "Accetti di utilizzare i Servizi solo per scopi leciti e in conformità con questi Termini. Ti impegni a non:",
      li1: "Utilizzare il Sito in modo che violi le leggi applicabili",
      li2: "Interferire con il corretto funzionamento del Sito",
      li3: "Utilizzare script automatizzati, bot o scraper per accedere eccessivamente al Sito",
      li4: "Tentare di ottenere accesso non autorizzato a qualsiasi parte del Sito",
      li5: "Riprodurre, distribuire o creare opere derivate senza permesso",
      heading4: "Accuratezza delle informazioni",
      p4: "Ci sforziamo di fornire risultati di conversione accurati. I nostri strumenti utilizzano fattori di conversione matematicamente esatti basati su standard consolidati (ISO, ANSI).",
      heading5: "Proprietà intellettuale",
      p5: "Tutti i contenuti del Sito sono proprietà di FeetToPixels e sono protetti dal diritto d'autore.",
      heading6: "Esclusione di garanzie",
      p6: "Il Sito e i Servizi sono forniti \"così come sono\" senza garanzie di alcun tipo.",
      heading7: "Limitazione di responsabilità",
      p7: "FeetToPixels non sarà in nessun caso responsabile per danni indiretti, incidentali, speciali o punitivi.",
      heading8: "Contenuti e link di terze parti",
      p8: "Il Sito può contenere link o pubblicità di terze parti. Non controlliamo contenuti di terze parti.",
      heading9: "Pubblicità",
      p9: "Il Sito visualizza pubblicità tramite reti pubblicitarie di terze parti, incluso Google AdSense.",
      heading10: "Privacy",
      p10: "L'uso del Sito è anche regolato dalla nostra Informativa sulla Privacy, incorporata in questi Termini.",
      heading11: "Modifiche ai termini",
      p11: "Ci riserviamo il diritto di modificare questi Termini in qualsiasi momento.",
      heading12: "Risoluzione",
      p12: "Ci riserviamo il diritto di terminare o limitare l'accesso al Sito senza preavviso.",
      heading13: "Legge applicabile",
      p13: "Questi Termini sono regolati dalle leggi degli Stati Uniti.",
      heading14: "Contatti",
      p14: "Per domande su questi Termini, contattaci tramite la nostra pagina di contatto.",
    },
  },
  nl: {
    faq: [],
    body: {
      lastUpdated: "Laatst bijgewerkt: 18 maart 2026",
      heading1: "Aanvaarding van voorwaarden",
      p1: "Door FeetToPixels (feettopixels.com) te bezoeken of te gebruiken, stemt u in met deze Servicevoorwaarden (\"Voorwaarden\"). Als u niet akkoord gaat, gebruik de Site dan niet.",
      heading2: "Beschrijving van de dienst",
      p2: "FeetToPixels biedt gratis online eenheidsconversietools, calculators en educatieve content over pixels, DPI, PPI en andere meeteenheden (\"Diensten\").",
      heading3: "Gebruik van de diensten",
      p3: "U stemt ermee in de Diensten alleen voor wettige doeleinden te gebruiken. U stemt ermee in het volgende niet te doen:",
      li1: "De Site gebruiken op een manier die toepasselijke wetten schendt",
      li2: "Proberen het correct functioneren van de Site te verstoren",
      li3: "Geautomatiseerde scripts, bots of scrapers gebruiken voor buitensporige toegang",
      li4: "Proberen ongeautoriseerde toegang te verkrijgen tot enig deel van de Site",
      li5: "Onze content zonder toestemming reproduceren, distribueren of afgeleide werken maken",
      heading4: "Nauwkeurigheid van informatie",
      p4: "We streven naar nauwkeurige conversieresultaten. Onze tools gebruiken wiskundig exacte conversiefactoren gebaseerd op vastgestelde standaarden (ISO, ANSI).",
      heading5: "Intellectueel eigendom",
      p5: "Alle content op de Site is eigendom van FeetToPixels en beschermd door auteursrecht.",
      heading6: "Uitsluiting van garanties",
      p6: "De Site en Diensten worden geleverd \"zoals ze zijn\" zonder enige garantie.",
      heading7: "Beperking van aansprakelijkheid",
      p7: "FeetToPixels is in geen geval aansprakelijk voor indirecte, incidentele, speciale of punitieve schade.",
      heading8: "Content en links van derden",
      p8: "De Site kan links of advertenties van derden bevatten. Wij controleren geen content van derden.",
      heading9: "Advertenties",
      p9: "De Site toont advertenties via advertentienetwerken van derden, waaronder Google AdSense.",
      heading10: "Privacy",
      p10: "Uw gebruik van de Site wordt ook beheerst door ons Privacybeleid.",
      heading11: "Wijzigingen van voorwaarden",
      p11: "Wij behouden ons het recht voor deze Voorwaarden op elk moment te wijzigen.",
      heading12: "Beëindiging",
      p12: "Wij behouden ons het recht voor uw toegang tot de Site zonder kennisgeving te beëindigen.",
      heading13: "Toepasselijk recht",
      p13: "Deze Voorwaarden worden beheerst door de wetten van de Verenigde Staten.",
      heading14: "Contact",
      p14: "Als u vragen heeft over deze Voorwaarden, neem dan contact met ons op via onze contactpagina.",
    },
  },
  ar: {
    faq: [],
    body: {
      lastUpdated: "آخر تحديث: 18 مارس 2026",
      heading1: "قبول الشروط",
      p1: "بالوصول إلى FeetToPixels (feettopixels.com) أو استخدامه، فإنك توافق على الالتزام بشروط الخدمة هذه (\"الشروط\"). إذا لم توافق على هذه الشروط، فلا تستخدم الموقع.",
      heading2: "وصف الخدمة",
      p2: "يوفر FeetToPixels أدوات مجانية لتحويل الوحدات عبر الإنترنت وحاسبات ومحتوى تعليمي يتعلق بالبكسل وDPI وPPI ووحدات القياس الأخرى (\"الخدمات\").",
      heading3: "استخدام الخدمات",
      p3: "أنت توافق على استخدام الخدمات فقط لأغراض مشروعة ووفقاً لهذه الشروط. أنت توافق على عدم:",
      li1: "استخدام الموقع بأي طريقة تنتهك القوانين المعمول بها",
      li2: "محاولة التدخل في الأداء السليم للموقع",
      li3: "استخدام النصوص البرمجية الآلية أو الروبوتات للوصول المفرط",
      li4: "محاولة الحصول على وصول غير مصرح به لأي جزء من الموقع",
      li5: "إعادة إنتاج أو توزيع أو إنشاء أعمال مشتقة بدون إذن",
      heading4: "دقة المعلومات",
      p4: "نسعى لتقديم نتائج تحويل دقيقة. تستخدم أدواتنا عوامل تحويل دقيقة رياضياً بناءً على معايير ثابتة (ISO، ANSI).",
      heading5: "الملكية الفكرية",
      p5: "جميع المحتوى على الموقع ملك لـ FeetToPixels ومحمي بحقوق النشر.",
      heading6: "إخلاء المسؤولية عن الضمانات",
      p6: "يُقدم الموقع والخدمات \"كما هي\" بدون أي ضمانات من أي نوع.",
      heading7: "تحديد المسؤولية",
      p7: "لن يكون FeetToPixels مسؤولاً بأي حال عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية.",
      heading8: "محتوى وروابط الطرف الثالث",
      p8: "قد يحتوي الموقع على روابط أو إعلانات لأطراف ثالثة. نحن لا نتحكم في محتوى الأطراف الثالثة.",
      heading9: "الإعلانات",
      p9: "يعرض الموقع إعلانات عبر شبكات إعلانية تابعة لجهات خارجية، بما في ذلك Google AdSense.",
      heading10: "الخصوصية",
      p10: "يخضع استخدامك للموقع أيضاً لسياسة الخصوصية الخاصة بنا.",
      heading11: "تعديل الشروط",
      p11: "نحتفظ بالحق في تعديل هذه الشروط في أي وقت.",
      heading12: "الإنهاء",
      p12: "نحتفظ بالحق في إنهاء أو تقييد وصولك إلى الموقع بدون إشعار.",
      heading13: "القانون المعمول به",
      p13: "تخضع هذه الشروط لقوانين الولايات المتحدة.",
      heading14: "اتصل بنا",
      p14: "إذا كانت لديك أسئلة حول هذه الشروط، يرجى التواصل معنا عبر صفحة الاتصال.",
    },
  },
  tr: {
    faq: [],
    body: {
      lastUpdated: "Son güncelleme: 18 Mart 2026",
      heading1: "Koşulların kabulü",
      p1: "FeetToPixels'e (feettopixels.com) erişerek veya kullanarak bu Hizmet Koşullarına (\"Koşullar\") bağlı olmayı kabul edersiniz. Bu Koşulları kabul etmiyorsanız, Siteyi kullanmayın.",
      heading2: "Hizmet açıklaması",
      p2: "FeetToPixels piksel, DPI, PPI ve diğer ölçü birimleriyle ilgili ücretsiz çevrimiçi birim dönüştürme araçları, hesaplayıcılar ve eğitim içeriği (\"Hizmetler\") sağlar.",
      heading3: "Hizmetlerin kullanımı",
      p3: "Hizmetleri yalnızca yasal amaçlarla ve bu Koşullara uygun olarak kullanmayı kabul edersiniz. Şunları yapmamayı kabul edersiniz:",
      li1: "Siteyi geçerli yasaları ihlal edecek şekilde kullanmak",
      li2: "Sitenin düzgün çalışmasını engellemeye çalışmak",
      li3: "Otomatik betikler, botlar veya kazıyıcılarla aşırı erişim",
      li4: "Sitenin herhangi bir bölümüne yetkisiz erişim girişiminde bulunmak",
      li5: "İzin olmadan içerik çoğaltmak, dağıtmak veya türev eserler oluşturmak",
      heading4: "Bilgi doğruluğu",
      p4: "Doğru dönüşüm sonuçları sunmaya çalışıyoruz. Araçlarımız yerleşik standartlara (ISO, ANSI) dayalı matematiksel olarak kesin dönüşüm faktörleri kullanır.",
      heading5: "Fikri mülkiyet",
      p5: "Sitedeki tüm içerik FeetToPixels'in mülkiyetindedir ve telif hakkı ile korunmaktadır.",
      heading6: "Garanti reddi",
      p6: "Site ve Hizmetler herhangi bir garanti olmaksızın \"olduğu gibi\" sunulur.",
      heading7: "Sorumluluk sınırlaması",
      p7: "FeetToPixels hiçbir durumda dolaylı, arızi, özel veya cezai zararlardan sorumlu olmayacaktır.",
      heading8: "Üçüncü taraf içerik ve bağlantılar",
      p8: "Site üçüncü taraf bağlantılar veya reklamlar içerebilir. Üçüncü taraf içeriğini kontrol etmiyoruz.",
      heading9: "Reklam",
      p9: "Site, Google AdSense dahil üçüncü taraf reklam ağları aracılığıyla reklam görüntüler.",
      heading10: "Gizlilik",
      p10: "Site kullanımınız Gizlilik Politikamız tarafından da yönetilir.",
      heading11: "Koşul değişiklikleri",
      p11: "Bu Koşulları herhangi bir zamanda değiştirme hakkını saklı tutarız.",
      heading12: "Fesih",
      p12: "Önceden bildirimde bulunmaksızın Site erişiminizi sonlandırma hakkını saklı tutarız.",
      heading13: "Geçerli hukuk",
      p13: "Bu Koşullar Amerika Birleşik Devletleri yasalarına tabidir.",
      heading14: "İletişim",
      p14: "Bu Koşullar hakkında sorularınız varsa, lütfen iletişim sayfamız aracılığıyla bize ulaşın.",
    },
  },
  pl: {
    faq: [],
    body: {
      lastUpdated: "Ostatnia aktualizacja: 18 marca 2026",
      heading1: "Akceptacja warunków",
      p1: "Korzystając z FeetToPixels (feettopixels.com), zgadzasz się na przestrzeganie niniejszych Warunków Korzystania z Usług (\"Warunki\"). Jeśli nie zgadzasz się z tymi Warunkami, nie korzystaj ze Strony.",
      heading2: "Opis usługi",
      p2: "FeetToPixels udostępnia bezpłatne narzędzia do konwersji jednostek online, kalkulatory i treści edukacyjne dotyczące pikseli, DPI, PPI i innych jednostek miary (\"Usługi\").",
      heading3: "Korzystanie z usług",
      p3: "Zgadzasz się korzystać z Usług wyłącznie w celach zgodnych z prawem i niniejszymi Warunkami. Zobowiązujesz się nie:",
      li1: "Używać Strony w sposób naruszający obowiązujące przepisy",
      li2: "Próbować zakłócać prawidłowe działanie Strony",
      li3: "Używać zautomatyzowanych skryptów, botów lub scraperów do nadmiernego dostępu",
      li4: "Próbować uzyskać nieautoryzowany dostęp do jakiejkolwiek części Strony",
      li5: "Reprodukować, dystrybuować lub tworzyć dzieła pochodne bez zezwolenia",
      heading4: "Dokładność informacji",
      p4: "Staramy się zapewniać dokładne wyniki konwersji. Nasze narzędzia używają matematycznie dokładnych współczynników opartych na ustalonych standardach (ISO, ANSI).",
      heading5: "Własność intelektualna",
      p5: "Wszystkie treści na Stronie są własnością FeetToPixels i są chronione prawem autorskim.",
      heading6: "Wyłączenie gwarancji",
      p6: "Strona i Usługi są dostarczane \"tak jak są\" bez jakichkolwiek gwarancji.",
      heading7: "Ograniczenie odpowiedzialności",
      p7: "FeetToPixels w żadnym wypadku nie ponosi odpowiedzialności za szkody pośrednie, przypadkowe, specjalne lub karne.",
      heading8: "Treści i linki osób trzecich",
      p8: "Strona może zawierać linki lub reklamy osób trzecich. Nie kontrolujemy treści osób trzecich.",
      heading9: "Reklamy",
      p9: "Strona wyświetla reklamy za pośrednictwem sieci reklamowych osób trzecich, w tym Google AdSense.",
      heading10: "Prywatność",
      p10: "Korzystanie ze Strony podlega również naszej Polityce Prywatności.",
      heading11: "Zmiany warunków",
      p11: "Zastrzegamy sobie prawo do zmiany niniejszych Warunków w dowolnym momencie.",
      heading12: "Rozwiązanie",
      p12: "Zastrzegamy sobie prawo do zakończenia lub ograniczenia dostępu do Strony bez powiadomienia.",
      heading13: "Prawo właściwe",
      p13: "Niniejsze Warunki podlegają prawu Stanów Zjednoczonych.",
      heading14: "Kontakt",
      p14: "Jeśli masz pytania dotyczące niniejszych Warunków, skontaktuj się z nami za pośrednictwem strony kontaktowej.",
    },
  },
  id: {
    faq: [],
    body: {
      lastUpdated: "Terakhir diperbarui: 18 Maret 2026",
      heading1: "Penerimaan ketentuan",
      p1: "Dengan mengakses atau menggunakan FeetToPixels (feettopixels.com), Anda setuju untuk terikat oleh Ketentuan Layanan ini (\"Ketentuan\"). Jika Anda tidak setuju, jangan gunakan Situs.",
      heading2: "Deskripsi layanan",
      p2: "FeetToPixels menyediakan alat konversi unit online gratis, kalkulator, dan konten edukasi terkait piksel, DPI, PPI, dan unit pengukuran lainnya (\"Layanan\").",
      heading3: "Penggunaan layanan",
      p3: "Anda setuju untuk menggunakan Layanan hanya untuk tujuan yang sah dan sesuai dengan Ketentuan ini. Anda setuju untuk tidak:",
      li1: "Menggunakan Situs dengan cara yang melanggar hukum yang berlaku",
      li2: "Mencoba mengganggu fungsi Situs yang semestinya",
      li3: "Menggunakan skrip otomatis, bot, atau scraper untuk akses berlebihan",
      li4: "Mencoba mendapatkan akses tidak sah ke bagian mana pun dari Situs",
      li5: "Mereproduksi, mendistribusikan, atau membuat karya turunan tanpa izin",
      heading4: "Akurasi informasi",
      p4: "Kami berusaha memberikan hasil konversi yang akurat. Alat kami menggunakan faktor konversi yang tepat secara matematis berdasarkan standar yang berlaku (ISO, ANSI).",
      heading5: "Kekayaan intelektual",
      p5: "Semua konten di Situs adalah milik FeetToPixels dan dilindungi oleh hak cipta.",
      heading6: "Penafian jaminan",
      p6: "Situs dan Layanan disediakan \"apa adanya\" tanpa jaminan apa pun.",
      heading7: "Batasan tanggung jawab",
      p7: "FeetToPixels tidak bertanggung jawab atas kerusakan tidak langsung, insidental, khusus, atau hukuman.",
      heading8: "Konten dan tautan pihak ketiga",
      p8: "Situs mungkin berisi tautan atau iklan pihak ketiga. Kami tidak mengontrol konten pihak ketiga.",
      heading9: "Periklanan",
      p9: "Situs menampilkan iklan melalui jaringan iklan pihak ketiga, termasuk Google AdSense.",
      heading10: "Privasi",
      p10: "Penggunaan Situs juga diatur oleh Kebijakan Privasi kami.",
      heading11: "Perubahan ketentuan",
      p11: "Kami berhak mengubah Ketentuan ini kapan saja.",
      heading12: "Penghentian",
      p12: "Kami berhak menghentikan atau membatasi akses Anda ke Situs tanpa pemberitahuan.",
      heading13: "Hukum yang berlaku",
      p13: "Ketentuan ini diatur oleh hukum Amerika Serikat.",
      heading14: "Hubungi kami",
      p14: "Jika Anda memiliki pertanyaan tentang Ketentuan ini, silakan hubungi kami melalui halaman kontak.",
    },
  },
  ru: {
    faq: [],
    body: {
      lastUpdated: "Последнее обновление: 18 марта 2026 г.",
      heading1: "Принятие условий",
      p1: "Получая доступ к FeetToPixels (feettopixels.com) или используя его, вы соглашаетесь с настоящими Условиями использования (\"Условия\"). Если вы не согласны с этими Условиями, не используйте Сайт.",
      heading2: "Описание сервиса",
      p2: "FeetToPixels предоставляет бесплатные онлайн-инструменты конвертации единиц, калькуляторы и образовательный контент, связанный с пикселями, DPI, PPI и другими единицами измерения (\"Сервисы\").",
      heading3: "Использование сервисов",
      p3: "Вы соглашаетесь использовать Сервисы только в законных целях и в соответствии с настоящими Условиями. Вы обязуетесь не:",
      li1: "Использовать Сайт способом, нарушающим применимое законодательство",
      li2: "Пытаться нарушить нормальную работу Сайта",
      li3: "Использовать автоматизированные скрипты, ботов или скраперы для чрезмерного доступа",
      li4: "Пытаться получить несанкционированный доступ к любой части Сайта",
      li5: "Воспроизводить, распространять или создавать производные работы без разрешения",
      heading4: "Точность информации",
      p4: "Мы стремимся предоставлять точные результаты конвертации. Наши инструменты используют математически точные коэффициенты на основе установленных стандартов (ISO, ANSI).",
      heading5: "Интеллектуальная собственность",
      p5: "Весь контент на Сайте является собственностью FeetToPixels и защищён авторским правом.",
      heading6: "Отказ от гарантий",
      p6: "Сайт и Сервисы предоставляются «как есть» без каких-либо гарантий.",
      heading7: "Ограничение ответственности",
      p7: "FeetToPixels ни в коем случае не несёт ответственности за косвенные, случайные, особые или штрафные убытки.",
      heading8: "Контент и ссылки третьих сторон",
      p8: "Сайт может содержать ссылки или рекламу третьих сторон. Мы не контролируем контент третьих сторон.",
      heading9: "Реклама",
      p9: "Сайт отображает рекламу через рекламные сети третьих сторон, включая Google AdSense.",
      heading10: "Конфиденциальность",
      p10: "Использование Сайта также регулируется нашей Политикой конфиденциальности.",
      heading11: "Изменения условий",
      p11: "Мы оставляем за собой право изменять настоящие Условия в любое время.",
      heading12: "Прекращение",
      p12: "Мы оставляем за собой право прекратить или ограничить ваш доступ к Сайту без уведомления.",
      heading13: "Применимое право",
      p13: "Настоящие Условия регулируются законодательством Соединённых Штатов.",
      heading14: "Контакты",
      p14: "Если у вас есть вопросы об этих Условиях, свяжитесь с нами через страницу контактов.",
    },
  },
};
